Cachedflowrecord
PaloAltoNetworks/gaia pull request #556
Opened 2020-10-05 16:52 UTC by philipatl

## Description

CachedFlowRecord is a new endpoint for enforcer to send incomplete flow reports, where one endpoint is a temporary PU. The backend will store these records until they can be reconciled (when a temporary PU becomes a real PU in the backend). The records may expire after 48 hours or more.

## Motivation and Context

Enforcer operational without backend https://docs.google.com/document/d/1hljv4ij8eqNO1Y0iSoAQYiq8bDWXs-8y1jqih0tyHiQ/edit#

## How Has This Been Tested?

none yet

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.

2020-10-06 21:00 UTC, primalmotion requested changes
Minus a minor name change request, it looks good

2020-10-06 21:00 UTC, primalmotion commented on specs/cachedflowrecord.spec
> +  package: zack
Note: package will need to change when we settle on the new service name.

2020-10-06 22:18 UTC, philipatl commented on specs/cachedflowrecord.spec
> +  - name: destinationIsLocalProcessingUnit
makes sense

2020-10-06 22:18 UTC, philipatl commented on specs/cachedflowrecord.spec
> +  package: zack
ok, that should be fine from our perspective

2020-10-16 00:46 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +    exposed: true
We will need a custom entity validator added here as well to ensure that *exactly one* of these fields is set to true. It's clearly an invalid state if both are true or false.

Here's an example of how to add a custom validator + unit tests: https://github.com/PaloAltoNetworks/gaia/pull/546/files#diff-6ac4082de0f6b763a7c3a2bd9445d3188936212ed4a899c1cb74a3bc837779ddR33-R36

2020-10-16 15:30 UTC, philipatl commented on specs/cachedflowrecord.spec
> +    exposed: true
I believe it would be possible for them both to be true (for localPU-to-localPU flow, where both enforcers are disconnected from the backend).

2020-10-16 21:53 UTC, aaslamin commented on custom_validations_test.go
> +		},
🏆

2020-10-16 21:56 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +    exposed: true
In that scenario, it must be possible to reconcile at least one side of connection since you just came up and created the PU(s). It will simplify the processing in the Control Plane by limiting at least one query to the database.

Depending on the data structure you are using in the Enforcer to maintain the cached flow reports, this could be an O(n) algorithm.

2020-10-16 21:58 UTC, aaslamin commented on constants/constants.go
> +	// AnnotationLocalPUID is the local PUID set by enforcer.
For benefit of future engineers, could we add to the comment explaining what a "local" PU ID is and its use cases.

2020-10-16 22:00 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +      bson_name: ai
👍

2020-10-16 22:00 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +      bson_name: aj
👀

2020-10-16 22:05 UTC, aaslamin commented
LGTM so far @philipatl  👌 ✨ 

I am currently figuring out the details of the reconciliation process on the Control Plane. As a result, we may need to add some indices to some of the models to aid in the process. Will get back to you here as I figure more out.

2020-10-16 22:09 UTC, aaslamin commented on specs/@flow.abs
> +  - timestamp
@philipatl @primalmotion this index are not be necessary for CachedFlowReports as they are only utilized for building the dependency map.

So instead, I believe we should only add this index only to FlowReports.

2020-10-16 22:11 UTC, aaslamin commented on specs/flowreport.spec
> +  - '@flow'
Beauty 😍

2020-10-17 00:10 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +    exposed: true
Another validation that should be done is when the `sourceType` or `destinationType` is a `ExternalNetwork`. In that situation, it is impossible that both `isLocalDestinationID` AND `isLocalSourceID` can be `true`.

2020-10-17 13:33 UTC, philipatl commented on constants/constants.go
> +	// AnnotationLocalPUID is the local PUID set by enforcer.
I adjusted the comment to contain more information.

2020-10-17 13:34 UTC, philipatl commented on specs/cachedflowrecord.spec
> +    exposed: true
added more validation

2020-10-17 13:34 UTC, philipatl commented on specs/@flow.abs
> +  - timestamp
I made the change, let me know if it looks right.

2020-10-19 17:19 UTC, aaslamin commented on constants/constants.go
> +	// AnnotationLocalPUID is set by enforcer to indicate the local PUID that backend should use to resolve CachedFlowRecords.
Thanks for the copy update!

Could you also add a small explanation describing what a "local PUID" is. I know it may feel slightly pedantic, but we will be hiring more developers in the near future so any relevant context we can provide now will go a long way to helping them out.

2020-10-19 17:31 UTC, aaslamin commented on custom_validations.go
> +	}
A consumer of the API will not be able to immediately identify what they did wrong based on the error copies provided here.

Perhaps, something along the lines of:

```
IsLocalSourceID cannot be set for the `SourceType` <whatever-they-have-configured>; it is only applicable when the 'SourceType' is set to `ProcessingUnit`.
```

2020-10-19 17:33 UTC, aaslamin commented on custom_validations_test.go
> +		},
✨ 💯

2020-10-19 17:37 UTC, aaslamin commented on specs/@flow.abs
> +  - timestamp
LGTM! Will let @primalmotion take a look as well to confirm.

We will likely need another two (or more) indexes on the cached flow reports model as well to aid w/ reconciliation in the Control Plane.

2020-10-19 20:47 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +  rest_name: cachedflowrecord
For consistency, could we rename this model to CachedFlow**Report** instead of CachedFlow**Record** as it encapsulates all the fields of a FlowReport.

2020-10-20 12:44 UTC, philipatl commented on constants/constants.go
> +	// AnnotationLocalPUID is set by enforcer to indicate the local PUID that backend should use to resolve CachedFlowRecords.
Yes, I was arbitrarily trying to stick to a one-line-comment per constant here. But I'm a fan of comments, so I'll expand on it.

2020-10-20 12:51 UTC, philipatl commented on specs/cachedflowrecord.spec
> +  rest_name: cachedflowrecord
It is ok with me, as long as we are all in agreement @t00f @primalmotion

2020-10-20 17:29 UTC, t00f commented on specs/cachedflowrecord.spec
> +  rest_name: cachedflowrecord
Yes please :)

2020-10-20 18:05 UTC, aaslamin commented on constants/constants.go
> +	AnnotationLocalPUID = "io:aporeto:enforcer:localpuid"
Hey @philipatl,

After speaking w/ @primalmotion, instead of an annotation, we should add a new optional field (_w/ the omit empty annotation_) to the PU resource to hold the local PUID.

This will allow the Control Plane to utilize a sparse index to retrieve PUs by their local PU ID making the reconciliation process significantly more efficient. By putting it inside the annotation, the Control Plane would be required to iterate all PUs which is extremely inefficient.

2020-10-20 18:49 UTC, philipatl commented on constants/constants.go
> +	AnnotationLocalPUID = "io:aporeto:enforcer:localpuid"
OK. Now the big question, what shall we call it? `LocalID`?

2020-10-20 18:52 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +  - $cachedflowrecord
@philipatl We will need two additional indexes added to the `CachedFlowReport` model to aid in the reconciliation process on the Control Plane:

- `sourceID`
- `destinationID`

2020-10-20 18:55 UTC, aaslamin commented on constants/constants.go
> +	AnnotationLocalPUID = "io:aporeto:enforcer:localpuid"
Naming is the toughest problem in CS...😅 

`LocalID` seems OK to me.

@primalmotion @t00f thoughts? Do you folks reckon this name will be future proof?

2020-10-20 19:00 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +  package: zack
@philipatl the name of the service will be `angeal`.

Some historic context for your amusement 🙃 

Control Plane services are named after Final Fantasy 7 (FF7) characters. Given that this service is related to the `zack` service (which deals with various other reports including FlowReports), I figured a character related to the Zack in FF7 would be appropriate. In the series, [Angeal Hewley was formerly an ally and mentor to Zack](https://en.wikipedia.org/wiki/Characters_of_the_Final_Fantasy_VII_series#Angeal_Hewley).

2020-10-20 19:02 UTC, aaslamin commented on specs/cachedflowrecord.spec
> +  - $cachedflowrecord
👀 FYI @primalmotion

2020-10-20 19:05 UTC, aaslamin commented on custom_validations.go
> +	}
Great, thanks for updating the error messages. Much clearer now! ✨

2020-10-20 19:06 UTC, aaslamin commented on custom_validations.go
> +	}
This has now been handled in a later commit :)

2020-10-20 19:08 UTC, aaslamin commented on constants/constants.go
> +	// AnnotationLocalPUID is set by enforcer to indicate the local PUID that backend should use to resolve CachedFlowRecords.
As per discussed, this description should now be added to the new local ID field that will be added to the Processing Unit resource.

2020-10-20 23:07 UTC, aaslamin commented on constants/constants.go
> +	AnnotationLocalPUID = "io:aporeto:enforcer:localpuid"
As discussed offline, we reached consensus on using `clientLocalID` as the field name.

2020-10-21 18:45 UTC, aaslamin commented on specs/processingunit.spec
> +    exposed: true
What is the purpose of this field? Do you expect it to be stored or is just for internal book keeping purposes on the enforcer?

The backend shouldn't care about this field I am guessing?

2020-10-21 19:01 UTC, philipatl commented on specs/processingunit.spec
> +    exposed: true
Ah, this and the similar field on `gaia.Alarm` is for enforcer to set when these things are created by enforcer when communication to backend is not available. (The other objects such as flow report have some kind of Timestamp field that enforcer can already set, and that backend respects.) Alarm and PU are different in that they have a `CreateTime` that is set from the backend at backend-creation time, but this may be confusing to users when it doesn't align with the actual creation time by enforcer.

2020-10-21 19:04 UTC, philipatl commented on specs/processingunit.spec
> +    exposed: true
This was discussed in a slack message after the design doc was written. I'll go back through the doc and make sure it's up to date.

2020-10-21 19:04 UTC, aaslamin commented on specs/processingunit.spec
> +    exposed: true
Ah ok, so do you want to Control Plane to use this timestamp if it is present when creating the PU?

2020-10-21 19:10 UTC, philipatl commented on specs/processingunit.spec
> +    exposed: true
Yes, the Control Plane should use this, but I'm not sure at what point in processing it needs to be handled. @primalmotion mentioned this about Alarms, so something similar may also apply to PUs

> ...since alarm are merged to avoid duplication. We can add a LastLocalTimestamp property and treat it correctly during merge, if any

2020-10-21 21:33 UTC, aaslamin approved these changes
LGTM @philipatl, great work.

@primalmotion could we get your 👍 as well.

2020-10-21 23:30 UTC, aaslamin commented on specs/processingunit.spec
> +    exposed: true
@philipatl I suppose we should also add a validation here then since this field is only semantically applicable IFF the `clientLocalID` field has been provided?

Is my reasoning correct?

2020-10-23 16:15 UTC, primalmotion approved these changes
LGTM. Let's have a review from @aaslamin also, to verify the model is working for VM

2020-10-23 23:44 UTC, merged