new: connection exception report
PaloAltoNetworks/gaia pull request #560
Opened 2020-10-14 19:01 UTC by sibicramesh

2020-10-14 19:33 UTC, t00f commented on specs/connectionexceptionreport.spec
> +    omit_empty: true
Do we need to have the destination informations? I thought it would be when the enforcer does not have a destination.

2020-10-14 19:46 UTC, sibicramesh commented on specs/connectionexceptionreport.spec
> +    omit_empty: true
This is the destination port that the client is trying to connect to.

2020-10-14 23:41 UTC, mheese commented on specs/connectionexceptionreport.spec
> +    - SynAckTransmitted
`SynAckTransmitted` as in seeing a connection timeout from the server side?

2020-10-14 23:43 UTC, sibicramesh commented on specs/connectionexceptionreport.spec
> +    - SynAckTransmitted
Yes, will be used when enforcer supports it in future.

2020-10-14 23:43 UTC, mheese commented on specs/connectionexceptionreport.spec
> +    omit_empty: true
Yes, we definitely need the destination information. That is exactly the information that PayPal wants to see. Otherwise the counters that we have right now would be enough.

2020-10-14 23:46 UTC, mheese commented on specs/connectionexceptionreport.spec
> +    description: ID of the destination processing unit.
I'm a bit confused here: we definitely should report the source PU ID of the PU where we observe the timeout.

However, if the `processingUnitID` and `processingUnitNamespace` are the destination one, then this could only be filled out during the `SynAckTransmitted` state?

2020-10-14 23:51 UTC, sibicramesh commented on specs/connectionexceptionreport.spec
> +    description: ID of the destination processing unit.
Yes, there will be no concept source or dest pu here, just the pu that encounters an expired connection. The info whether its source or dest is irrelevant in my opinion. But you can deduce it through the state as you mentioned, `SynAckTransmitted ` will only be reported in server side.

2020-10-16 00:25 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "207961945f19e30e0c4bf7865bebe2b89d027bd3",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "1cd51ec9e6f61c7f52be960a22126c3be73779b7",
    "pipeline": "master"
  }
]
```

2020-10-16 00:35 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "1cd51ec9e6f61c7f52be960a22126c3be73779b7",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "0153e015152b77f45c36a648edabcb3b7e5a74ec",
    "pipeline": "master"
  }
]
```

2020-10-16 02:18 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "f96e0d3a868f85b95a1de7e9ec9ee902a194e4ea",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "1cd51ec9e6f61c7f52be960a22126c3be73779b7",
    "pipeline": "master"
  }
]
```

2020-10-16 06:00 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "39e2f29eeca7f18c32d358e1f51a196e5d061f3c",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "1cd51ec9e6f61c7f52be960a22126c3be73779b7",
    "pipeline": "master"
  }
]
```

2020-10-16 17:48 UTC, mheese commented on specs/connectionexceptionreport.spec
> +  - name: remoteController
I still think that this should be called `destinationController` and `destinationProcessingUnitID`. The description should make it clear that this can only be set in the SynAckTransmitted/AckTransmitted state cases. And it aligns it with `destinationIP` and `destinationPort`

2020-10-19 04:31 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "de504ff68b608b7c4828fd5f70272396652d62f0",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "a6c38965ace1678518a6928a7fdc236c8500f3ca",
    "pipeline": "master"
  }
]
```

2020-10-20 22:15 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "8b666fb176ccd55f1bf25b6e692dc52967967b47",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "774f65408373c895b29da57e4bbb5b9830f68588",
    "pipeline": "master"
  }
]
```

2020-10-20 23:43 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "c9ee4c143509eeecaa17a71793ee2284b2c95142",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "774f65408373c895b29da57e4bbb5b9830f68588",
    "pipeline": "master"
  }
]
```

2020-10-21 01:51 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "14e67e9f2bd572c9da5664e6e7abf5bfb70196f9",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-21 02:02 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "d187824f7ace3b61643508c105174b4f4b8ae32e",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 00:29 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "4448354e6e9466423728f454769678764b6cbf11",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 00:29 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "d3a7698fbc9cf85775b0fef583578342200a92df",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 02:07 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "4e93bed940b4b021acf04c6365cc886189338350",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 02:57 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "48354bef053eaf0e8ee00fc08c700b961c090a7f",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 03:00 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "de94fab33e5d9c87e8814b49a657cf28fe170ee6",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 05:00 UTC, aaslamin requested changes
Overall looks good, just a few changes required!

Please get one last set of  👀 from @primalmotion before merging.

2020-10-22 05:01 UTC, aaslamin commented on specs/statsquery.spec
> +    - ConnectionExceptions
👍

2020-10-22 05:01 UTC, aaslamin commented on specs/statsinfo.spec
> +    - ConnectionExceptions
👍

2020-10-22 05:41 UTC, sibicramesh commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "failed-connections-reporter",
    "component": "enforcerd",
    "pr-id": "2062",
    "commit-sha": "bbf4c062135cf7552007f15f7f487371319f6759",
    "pipeline": "master"
  },
  {
    "project": "failed-connections-reporter",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "cfb902ee21472dbb4556e17598c258029b442e5e",
    "pipeline": "master"
  }
]
```

2020-10-22 19:22 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "cdffbecc9aba7eea654517eb536d9f96ef05f50a",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "9e89470e65813ac126a93dee2fd92952170c0a92",
    "pipeline": "master"
  }
]
```

2020-10-22 21:49 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "730058672e756395c4a93d20253ef23f9af71918",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "9e89470e65813ac126a93dee2fd92952170c0a92",
    "pipeline": "master"
  }
]
```

2020-10-22 22:33 UTC, aaslamin commented on specs/connectionexceptionreport.spec
> +- - namespace
@jping0929 Actually, this should be `enforcernamespace` as your report doesn't contain a `namespace` field.

2020-10-22 22:35 UTC, aaslamin commented on specs/connectionexceptionreport.spec
> +- - namespace
So it should be:

```

```
# Indexes
indexes:
- - processingUnitNamespace
  - timestamp
- - enforcernamespace
  - timestamp
```
```

2020-10-22 23:34 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "487cce3fda9d786951fbca570181253af873c9ca",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "9e89470e65813ac126a93dee2fd92952170c0a92",
    "pipeline": "master"
  }
]
```

2020-10-23 00:50 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "09dde1458bbe64aabce1e69d87f154320ff13f33",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "9e89470e65813ac126a93dee2fd92952170c0a92",
    "pipeline": "master"
  }
]
```

2020-10-23 04:34 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "62b678a6e8e7c847fc5d4eb92ee8cbab2875d810",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "9e89470e65813ac126a93dee2fd92952170c0a92",
    "pipeline": "master"
  }
]
```

2020-10-23 06:22 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "62b678a6e8e7c847fc5d4eb92ee8cbab2875d810",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "a60fe2205d6090a65eed9e87c537feace1c5fc3e",
    "pipeline": "master"
  }
]
```

2020-10-23 18:18 UTC, jping0929 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "connection-exception-backend",
    "component": "backend",
    "pr-id": "889",
    "commit-sha": "87a49b7760828564ba4c571bff99d6b4e43fb06a",
    "pipeline": "master"
  },
  {
    "project": "connection-exception-backend",
    "component": "gaia",
    "pr-id": "560",
    "commit-sha": "a60fe2205d6090a65eed9e87c537feace1c5fc3e",
    "pipeline": "master"
  }
]
```

2020-10-23 22:49 UTC, t00f approved these changes
LGTM, congratulations on your first PR :)

2020-10-23 22:55 UTC, merged