new: initiate gaia spec for enforcer auto upgrade
PaloAltoNetworks/gaia pull request #562
Opened 2020-10-23 02:32 UTC by t00f

PR for the enforcer auto upgrade feature (https://redlock.atlassian.net/browse/CNS-33)

> Fixes https://redlock.atlassian.net/browse/CNS-268

2020-10-23 02:34 UTC, t00f commented on specs/enforcer.spec
> -    description: If `true`, the enforcer version is outdated and should be updated.
@primalmotion I can't remember why we have this attribute and if it's still used or not?

2020-10-26 18:21 UTC, brianonn commented on specs/enforcer.spec
> +    description: Defines the next version the enforcer will be upgraded to.
we also talked about downgrades / rollbacks. and in that context using `upgradeTargetVersion` might not make semantic sense.   How about `requestedTargetVersion` ? 
```
description: Defines the next version the enforcer will be moved to
```

2020-10-26 18:23 UTC, brianonn commented on specs/enforcer.spec
> +    default_value: None
maybe just `None`, `Requested` and `Upgrading` but then, we also talked about upgrades and rollbacks, so I want to be able to cover that.  Meaning, maybe lets use simply `None`, `Requested` and `InProgress` states.

2020-10-26 18:27 UTC, brianonn commented on specs/enforcer.spec
> +  - name: upgradeStatus
since we wanted to consider upgrades and rollbacks as operationally similar things, maybe this property can be called `targetStatus` to follow along with the idea I presented below, `requestedTargetVersion`

2020-10-26 18:29 UTC, brianonn commented on specs/enforcer.spec
> +    default_value: None
if we call `upgradeStatus` as `targetVersionStatus` (see line 273)  then these three states can be `None`, `ChangeRequested` and `InProgress`

2020-10-26 18:35 UTC, brianonn commented on specs/enforcerrefresh.spec
> +
who sets the recursive flag, and who consumes it? I don't need it at the enforcer object but maybe it's needed by the UI to tell the backend something?  I just want to understand how it's used 

Also, I want to remove the word 'upgrade' as a prefix on these properties, since we want to try to consider an upgrade and a rollback operationally the same thing i.e. it's just a version change at the enforcer.  

So I've been trying to think of these as simply a `targetVersion` or `requestedVersion` and use that as a prefix instead of `upgrade...`

2020-10-26 18:40 UTC, brianonn commented on specs/enforcerrefresh.spec
Marcus and I had also tossed about the idea of using a `refreshType` (or can be simply `type` ) field on the enforcerrefresh spec. so that we can differentiate between a debug type refresh and a `change version` type of refresh.   I.e. we thought maybe we needed an enum here for this purpose.   

Granted, we can assume one type or the other based on what fields are actually populated in the refresh we see, but this is not always the right way to do it.

2020-10-30 18:43 UTC, brianonn commented on specs/namespace.spec
>    - name: name
@t00f Indeed at one point we talked about a `minimumEnforcerVersion` but I believe it was resolved to be the `requestedEnforcerVersion` instead.  i.e. we don't want to imply that there is any policy level enforcement of this minimum.  

Antoine @primalmotion can add his thoughts here as well, but I think this `minimumEnforcerVersion` should be called `desiredEnforcerVersion` or even `bootstrapEnforcerVersion` to indicate that it is used when new enforcers startup and register into the namespace. 

Actually, the name `bootstrapEnforcerVersion` has some appeal since it corresponds to the new install / upgrade flow that we are designing, where the `bootstrap` code starts up in an AMI and launches the `core` /  `updater` process which  then downloads and bootstraps the enforcer in this namespace, using the version in this field, or walking up the namespace hierarchy to the parents until it finds one (like CA), or when not present and not found on the parent paths then it will use the latest enforcer version.

2020-10-30 18:50 UTC, brianonn commented on specs/namespace.spec
>    - name: name
could also be `initialEnforcerVersion` or `defaultEnforcerVersion`

2020-10-30 19:10 UTC, t00f commented on specs/enforcerrefresh.spec
> +
The recursive will be useful in the case we want the "upgrade" to happen in a namespace recursively. 

If you receive an enforcerRefresh with `namespace: /cns` and `upgradeRecursive: true`, it means all enforcers in /cns and below should be "upgraded".

2020-10-30 19:16 UTC, t00f reviewed
These are valid comments, thanks Brian.

I am suggesting to use `migrate` instead of `upgrade`:

* `migrationVersion` : Defines the next version the enforcer will be moved to
* `migrationStatus` (None, Requested, Migrating): Define the migration status
* `migrationSelector`: Define which enforcers are targeted by the migration
* `migrationRecursive`: Define if the migration should be recursive in the given namespace
* `defaultEnforcerVersion` makes more sense to me

Note: The UI will talk about upgrade, and not migration, correct?
What do you think?

2020-10-30 19:44 UTC, primalmotion commented on specs/enforcer.spec
> -    description: If `true`, the enforcer version is outdated and should be updated.
It's not. Can be removed

2020-10-30 19:45 UTC, primalmotion commented on specs/enforcer.spec
> +  - name: upgradeStatus
Fine by me

2020-10-30 19:46 UTC, primalmotion commented on specs/enforcer.spec
> +  - name: upgradeStatus
This property is read only

2020-10-30 19:47 UTC, primalmotion commented on specs/enforcer.spec
> +    description: Defines the next version the enforcer will be upgraded to.
This property is read only. No need for validation here

2020-10-30 19:48 UTC, primalmotion commented on specs/enforcerrefresh.spec
Yeah. We should have a enum for type

2020-10-30 19:50 UTC, primalmotion requested changes

2020-10-30 19:50 UTC, primalmotion commented on specs/enforcerrefresh.spec
> +    read_only: true
This property is not read only

2020-10-30 19:50 UTC, primalmotion commented on specs/enforcerrefresh.spec
> +  - name: upgradeRecursive
Not read only

2020-10-30 19:50 UTC, primalmotion commented on specs/enforcerrefresh.spec
> +    read_only: true
Not auto generated

2020-10-30 19:50 UTC, primalmotion commented on specs/enforcerrefresh.spec
> +    read_only: true
Not read only and not autogenerated

2020-10-31 00:11 UTC, t00f commented
@brianonn @primalmotion I addressed all your comments in the latest changes. We are now talking about a "migration" of the enforcer instead of an "upgrade"

2020-11-02 19:02 UTC, t00f commented
#### Notes

* Enforcer -> Check version `migrationAvailableVersion` 
* UI sends an enforcerRefresh  Enforcer Push -> Status = Running
  * a) Success = `migrationAvailableVersion`=null + Status = None
  * b) Failure = keep `migrationAvailableVersion` + Status = Failed + Send an alarm + event log.
* /!\ In the processor of enforcerRefresh, If no parentID, requires a selector
* Avoid the semver dependency

2020-11-04 17:58 UTC, brianonn commented
I commented in Slack already on Monday, but I'll also just add my approval here.
It looks good, let's go with this and I'll use this PR with the enforcer to develop it out in the next sprints.

2020-11-04 18:05 UTC, brianonn commented
> These are valid comments, thanks Brian.
> 
> I am suggesting to use `migrate` instead of `upgrade`:
> 
> * `migrationVersion` : Defines the next version the enforcer will be moved to
> * `migrationStatus` (None, Requested, Migrating): Define the migration status
> * `migrationSelector`: Define which enforcers are targeted by the migration
> * `migrationRecursive`: Define if the migration should be recursive in the given namespace
> * `defaultEnforcerVersion` makes more sense to me
> 
> Note: The UI will talk about upgrade, and not migration, correct?
> What do you think?

I suppose the UI can also be smart about it and present [ Upgrade ] or [ Downgrade ] buttons if it has all the knowledge about the semantic ordering of the currentVersion and the `nextAvailableVersion`  

@primalmotion @t00f With `nextAvailableVersion` , do you think we also need a `desiredVersion` or `requestedVersion` ?
I'm a little confused on the intended use for `nextAvailableVersion`.  That name makes it seem like it's informational only, but then it's also to be used to migrate to? so it's actually the `requestedVersion`... do we need both ?

2020-11-04 18:14 UTC, t00f commented
@brianonn,

`nextAvailableVersion` is to provide which version the enforcer should be **updated**. If a user is planning a rollback, the `migrationVersion` is the one that is sent in the enforcerRefresh notification

2020-11-04 18:35 UTC, brianonn commented
> @brianonn,
> 
> `nextAvailableVersion` is to provide which version the enforcer should be **updated**. If a user is planning a rollback, the `migrationVersion` is the one that is sent in the enforcerRefresh notification

ok thanks for the clarification! @t00f

2020-11-10 04:27 UTC, ericrpowers commented on custom_validations.go
> +}
We probably need to handle empty string here as `defaultEnforcerVersion` is not a required value:
```
	if data == "" {
		return nil
	}
```

2020-11-10 23:20 UTC, ericrpowers submitted a review, later dismissed

2020-11-10 23:55 UTC, t00f commented
Resync'ed with latest changes from Amir :)

2020-11-11 00:06 UTC, ericrpowers approved these changes

2020-11-11 22:31 UTC, merged