Add namespacetypes endpoint
PaloAltoNetworks/gaia pull request #566
Opened 2020-10-30 17:23 UTC by vjuux

## Description

Add `/namespacetypes` endpoint which returns the type of the current namespace (passed in the X-Namespace header).

2020-10-30 18:49 UTC, ericrpowers reviewed
I think you missed committing `namespacetype.go`?

2020-10-30 18:49 UTC, ericrpowers commented on .spelling
> +NamespaceType
Should be above `NamespaceUnique`

2020-10-30 18:49 UTC, ericrpowers commented on specs/namespacetype.spec
> +    Returns the type of the current namespace (passed in the X-Namespace header).
```
Returns the type of the specified namespace.
```
You can drop the stuff in the parentheses as that is the only way to pass in the namespace. Also, for formatter does not like the use of `|-` in the description for me.

2020-10-30 18:49 UTC, ericrpowers commented on specs/namespacetype.spec
> +    type: string
You may want to make this an `enum` like namespace has for its type and use the same `allowed_choices` (I noticed that your branch is a bit behind so merge in master for the latest types).

2020-10-30 18:49 UTC, ericrpowers commented on specs/root.spec
> +    description: Returns the type of the current namespace (passed in the X-Namespace header).
```
Returns the type of the specified namespace.
```

2020-10-30 19:09 UTC, vjuux commented on specs/namespacetype.spec
> +    Returns the type of the current namespace (passed in the X-Namespace header).
I've seen this `|-` in multiple places, wondering why would it trip over this

2020-10-30 19:10 UTC, vjuux commented
@ericrpowers This should be better now :p

2020-10-30 21:41 UTC, ericrpowers commented on specs/namespacetype.spec
> +    - Group
This is an old namespace type. You need to pull in latest master for the revised types (and updated description).

2020-11-02 17:21 UTC, t00f commented on specs/namespacetype.spec
> +    Returns the type of the current namespace (passed in the X-Namespace header).
`|-` is used for multiline text

2020-11-02 19:23 UTC, t00f requested changes

2020-11-02 19:23 UTC, t00f commented on specs/namespacetype.spec
> +  - name: type
`type` is a keyword in golang, let's name it `namespaceType`.

You don't need an enum here, just put a string that is readonly.
* No default value, no transient.
* readonly, autogenerated

2020-11-02 20:15 UTC, vjuux commented on specs/namespacetype.spec
> +  - name: type
It seems that I'm missing something here, don't understand why we're using type `string` over `enum` with default value :/

2020-11-03 18:13 UTC, t00f approved these changes
LGTM, thanks @vjuux !

2020-11-03 18:26 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "b6990769d4459fa1584d379c7e39f4758f296fe1",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "dcec287c8320167e3069da11c20ab449397bcf11",
    "pipeline": "master"
  }
]
```

2020-11-03 18:34 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "22ef074416cc7f3ab7869060950ac02eb66765f6",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "dcec287c8320167e3069da11c20ab449397bcf11",
    "pipeline": "master"
  }
]
```

2020-11-03 18:42 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "dcec287c8320167e3069da11c20ab449397bcf11",
    "pipeline": "master"
  }
]
```

2020-11-03 20:25 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "1c76f7da1f6d98e5fb3ca295c6ac6669244c66d5",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  }
]
```

2020-11-03 21:37 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "db74446bf134275143849b4fb0f1c4bb032a6d07",
    "pipeline": "master"
  }
]
```

2020-11-03 22:24 UTC, t00f approved these changes
LGTM

2020-11-03 22:54 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "db74446bf134275143849b4fb0f1c4bb032a6d07",
    "pipeline": "master"
  }
]
```

2020-11-03 23:06 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "7d41faf69bb26128d649f8fcb73a5d2f9b2364f9",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  }
]
```

2020-11-03 23:45 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespacetype",
    "component": "gaia",
    "pr-id": "566",
    "commit-sha": "39dc7d9384413502ab63ba19ee4e94b427360fd9",
    "pipeline": "master"
  },
  {
    "project": "namespacetype",
    "component": "backend",
    "pr-id": "903",
    "commit-sha": "c544f642a6c1a573e6e650d6fd6d6f6c8264e857",
    "pipeline": "master"
  }
]
```

2020-11-04 16:52 UTC, merged