New: Tag prefixes for namespace policy suggestion
PaloAltoNetworks/gaia pull request #577
Opened 2020-12-01 19:40 UTC by ericrpowers

#### Description
To narrow down suggestions and help make things a bit more lightweight, we want to add a list of tag prefixes that will be used to suggest policies. Only these tags will be transmitted on the wire.

2020-12-01 19:43 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "67341789017016dbe86a5e6cf66a9f1a6ad71a9b",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "a9d17fcce4e45ab971616c870626878c0f4498c5",
    "pipeline": "master"
  }
]
```

2020-12-01 19:49 UTC, t00f submitted a review, later dismissed
Lgtm

2020-12-01 21:48 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "ab32c457bffc3a56290f4ade9e8cd0fe0b83ae6e",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "a9d17fcce4e45ab971616c870626878c0f4498c5",
    "pipeline": "master"
  }
]
```

2020-12-02 22:21 UTC, t00f commented
@dstiliadis @primalmotion @mheese please have a look - will merge this PR by EOD otherwise

2020-12-02 23:44 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "4515ac331f76f7a84bab8f676def81216284950e",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "a9d17fcce4e45ab971616c870626878c0f4498c5",
    "pipeline": "master"
  }
]
```

2020-12-03 03:36 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "9c1ffdb1e032ebef5190bec53db3d6a42871f7bb",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "26b5f8451255f237648875b0ab6540f31cf0a221",
    "pipeline": "master"
  }
]
```

2020-12-03 19:45 UTC, primalmotion requested changes

2020-12-03 19:45 UTC, primalmotion commented on specs/namespacepolicyinfo.spec
> +    stored: true
These props are not stored and are read only,

2020-12-03 19:45 UTC, primalmotion commented on specs/root.spec
> +    description: Modifies the policy info of the specified namespace.
Nope. Only get here. You must have access to the real namespace

2020-12-03 20:29 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "e476a7e26d7602460ebfd18a892a4e9b66b83a99",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "8c23c8a77bd08f991b9ff0a134b209d496ad6bd1",
    "pipeline": "master"
  }
]
```

2020-12-03 21:02 UTC, primalmotion approved these changes

2020-12-03 21:08 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tag-prefixes",
    "component": "backend",
    "pr-id": "937",
    "commit-sha": "447dead73661c0f6ed7ac8c7c127c00910515017",
    "pipeline": "master"
  },
  {
    "project": "tag-prefixes",
    "component": "gaia",
    "pr-id": "577",
    "commit-sha": "8c23c8a77bd08f991b9ff0a134b209d496ad6bd1",
    "pipeline": "master"
  }
]
```

2020-12-03 23:29 UTC, merged