new: expose the VictoriaMetrics' '/api/v1/query' endpoint
PaloAltoNetworks/gaia pull request #600
Opened 2020-12-19 03:01 UTC by aaslamin

This PR exposes the VM `/api/v1/query` endpoint so clients can make "[instant queries](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries)" and renames the APIs as follows:

1. `[GET|POST] /metricsquery` _(proxy API to vm's /api/v1/query endpoint)_
2. `[GET|POST] /metricsqueryrange` _(proxy API to vm's /api/v1/query_range endpoint)_

2020-12-22 02:15 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "e20bae2e5d2dc0d2a9c814a0cc6c622da9d3d8f1",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "d1b6480f246fd1447df59375c08a4c7f3b6ca2e1",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "c9faefcaa02bf6e3e1ee9399f6ddcf837e682025",
    "pipeline": "master"
  }
]
```

2020-12-23 00:27 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "15f35dd4c2ea64cf19daa78848b1869e80c26f1a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "c735590772d38a9b16c1c8f193ded5c0f8757d61",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "0258006c3c4171332828731eb2ab851d511e8eef",
    "pipeline": "master"
  }
]
```

2021-01-06 17:36 UTC, primalmotion requested changes

2021-01-06 17:36 UTC, primalmotion commented on specs/root.spec
> +    description: Verify the validity of a token. This is deprecated. You should use Create.
this does not seem formatted correctly. regolithe extention limts the line lenght.

2021-01-11 22:05 UTC, aaslamin commented on specs/root.spec
> +    description: Verify the validity of a token. This is deprecated. You should use Create.
Interesting, I ran:

`cat specs/root.spec | rego format > not-spec.go && mv not-spec.go specs/root.spec`

And it modified these lines. Is there something else I should be doing?

2021-01-11 22:41 UTC, aaslamin commented on specs/root.spec
> +    description: Verify the validity of a token. This is deprecated. You should use Create.
Update: you must use the vscode extension to enforce the line lengths. The rego CLI is not doing this.

2021-01-11 22:45 UTC, aaslamin commented on specs/root.spec
> +    description: Verify the validity of a token. This is deprecated. You should use Create.
Fixed ✅

2021-01-12 17:27 UTC, primalmotion submitted a review, later dismissed

2021-01-12 18:07 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "230427123efd1b0bd7fb337b8c51fc610721ea86",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "341d3b4afae0015229548b791fb4897ffe6f904b",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "181a7f40cf0fe2008b8c86ac40f3ef988e16c0ea",
    "pipeline": "master"
  }
]
```

2021-01-12 18:23 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "230427123efd1b0bd7fb337b8c51fc610721ea86",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "341d3b4afae0015229548b791fb4897ffe6f904b",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "c3fc9145aefac6440bc7eed4cfd2edb6573f562c",
    "pipeline": "master"
  }
]
```

2021-01-19 02:14 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "45303bb4ebc1e05079c98ce82d038f6141c072be",
    "pipeline": "master"
  }
]
```

2021-01-19 10:32 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "573e57e5bac5360c2ce9f98124d0915ee3b91234",
    "pipeline": "master"
  }
]
```

2021-01-19 19:32 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "82e6c18ed0924f578fa38a4427b524a55d640123",
    "pipeline": "master"
  }
]
```

2021-01-19 20:03 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "c51ab999e867832338b217f4d6af084b3388eed1",
    "pipeline": "master"
  }
]
```

2021-01-19 21:03 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "dd26fc4e06eb124d7a3e008cdef1e9dae6f66cb5",
    "pipeline": "master"
  }
]
```

2021-01-19 21:44 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "cef02289b6c76fc46594503efe8307775a46dd10",
    "pipeline": "master"
  }
]
```

2021-01-19 22:30 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "cef02289b6c76fc46594503efe8307775a46dd10",
    "pipeline": "master"
  }
]
```

2021-01-19 23:26 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm_instant_query",
    "component": "gaia",
    "pr-id": "600",
    "commit-sha": "681d3660e5b00674ce186c8b07f6fc7aa457803a",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "underwater",
    "pr-id": "129",
    "commit-sha": "b30679dc1924cd36b9cc5e6665a2fe8f54662bab",
    "pipeline": "master"
  },
  {
    "project": "vm_instant_query",
    "component": "backend",
    "pr-id": "982",
    "commit-sha": "d43578d1ac30231de892980f13c31585e12b5f52",
    "pipeline": "master"
  }
]
```

2021-01-20 22:50 UTC, primalmotion approved these changes

2021-01-21 00:35 UTC, merged