Cloud data ingestion graph model
PaloAltoNetworks/gaia pull request #603
Opened 2021-01-21 18:12 UTC by dstiliadis

## Description

Includes the APIs for graph data ingestion.

2021-03-19 21:28 UTC, itsai220 commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "9dbb1ded25ddb2eadd636b7752d62bd746de39cf",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "3eb7a18177f5214794bf745515e330e6f05dfc54",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "309e311938ed7382f4449fff01c8b4578bd15208",
    "pipeline": "master"
  }
]
```

2021-03-19 23:41 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "9dbb1ded25ddb2eadd636b7752d62bd746de39cf",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "3eb7a18177f5214794bf745515e330e6f05dfc54",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "3feddb06400380c91cad08c4a87ded6f1cd8161f",
    "pipeline": "master"
  }
]
```

2021-03-19 23:47 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "9dbb1ded25ddb2eadd636b7752d62bd746de39cf",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "3eb7a18177f5214794bf745515e330e6f05dfc54",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c9b7de7e9cca4234e8384fbbd387d9864ef687dd",
    "pipeline": "master"
  }
]
```

2021-03-20 00:28 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "caf88e5f09b2611fb3b08fd107c40c43437e3d5e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "3eb7a18177f5214794bf745515e330e6f05dfc54",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c9b7de7e9cca4234e8384fbbd387d9864ef687dd",
    "pipeline": "master"
  }
]
```

2021-03-20 00:44 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "3eb7a18177f5214794bf745515e330e6f05dfc54",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c9b7de7e9cca4234e8384fbbd387d9864ef687dd",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "5b08d1a645ef05a3857d6cbda83be887abdf84c9",
    "pipeline": "master"
  }
]
```

2021-03-20 20:18 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "2ef51fcf9ade34b25463367e869561c226a4460f",
    "pipeline": "master"
  }
]
```

2021-03-20 20:23 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "ccf3294509f27fd6aedd73a08afd1d3399e22672",
    "pipeline": "master"
  }
]
```

2021-03-20 20:29 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "270923312fa6594143d7448968e4426e4bd15de3",
    "pipeline": "master"
  }
]
```

2021-03-20 20:36 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "7e9d3c6ebc7001fe9451ce35b6bea0c69beab10d",
    "pipeline": "master"
  }
]
```

2021-03-20 20:40 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "3758d38f309b520994a919039d011d15a1d985c4",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  }
]
```

2021-03-20 21:17 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "ab71c8d1bfd0625a13318a9831d9e3554739f4b8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "6a7d4449f087239e3db996f1c35f4f5b8d3ae7b5",
    "pipeline": "master"
  }
]
```

2021-03-20 21:24 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "6a7d4449f087239e3db996f1c35f4f5b8d3ae7b5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "876fc3b5efe01d95b7dacd9260e86a702d3ebc89",
    "pipeline": "master"
  }
]
```

2021-03-20 21:25 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "876fc3b5efe01d95b7dacd9260e86a702d3ebc89",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "78b2188cb767ed4d15a2f119485676abad94b1b0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  }
]
```

2021-03-21 01:58 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d407d8d97dc43372d399edab5f5efa9bd7112d2b",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "889708620db354667314479ad2c43b0b208a3200",
    "pipeline": "master"
  }
]
```

2021-03-21 18:06 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d407d8d97dc43372d399edab5f5efa9bd7112d2b",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "04060ab5359599bc0be6ceef54913782aac1ed3d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  }
]
```

2021-03-22 00:57 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d407d8d97dc43372d399edab5f5efa9bd7112d2b",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "802648b669ceac7ab33cff015560cd6b5a38d6f9",
    "pipeline": "master"
  }
]
```

2021-03-22 01:58 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d407d8d97dc43372d399edab5f5efa9bd7112d2b",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "ab29d113758184e2d63392c355360841c0042c3d",
    "pipeline": "master"
  }
]
```

2021-03-22 16:39 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d407d8d97dc43372d399edab5f5efa9bd7112d2b",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "1b764145210a6db2e3b6da652f2d05b390060705",
    "pipeline": "master"
  }
]
```

2021-03-22 19:27 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6ea39cf0ba66752e8fb22b10baa95a278ed1f085",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d6cb6944484154f8b169a47b72e86621f00d4708",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "1d7a28271a9c67e08bad9d32cd5994f8bba3e91c",
    "pipeline": "master"
  }
]
```

2021-03-23 06:15 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "69874918d0e5ccb63d22f157b6a64c715492feba",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f760f6976d58c5dbb25fc236baf8f4b0befcd0fb",
    "pipeline": "master"
  }
]
```

2021-03-23 06:17 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "69874918d0e5ccb63d22f157b6a64c715492feba",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "036af4fc0dce56cdc823f7f9c92d074f9104d2d0",
    "pipeline": "master"
  }
]
```

2021-03-23 06:42 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "69874918d0e5ccb63d22f157b6a64c715492feba",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "66aed3b811d5630f8ae1933a949bae90d7418dc0",
    "pipeline": "master"
  }
]
```

2021-03-23 15:11 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "69874918d0e5ccb63d22f157b6a64c715492feba",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "7afbfb9dc0c1dd9b48fca3df519eaf1558c174ca",
    "pipeline": "master"
  }
]
```

2021-03-23 15:16 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "69874918d0e5ccb63d22f157b6a64c715492feba",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "e1223d07ef0d81a773a27d0de26cf393580a325e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  }
]
```

2021-03-23 16:09 UTC, primalmotion requested changes
- global problem of misused of `autogenerated`
- probably tons of properties that must be in `read_only` or `creation_only`.
- inconsistent package names
- missing indexes in `@prismabase.abs`

Please fix as much as possible, even the parts I missed since this will need a complete re-review and that's a huge PR

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudnode.spec
> +  - name: relatedObjectID
I fell there are a ton of properties that should be readonly. Please recheck all the properties

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudnode.spec
> +    autogenerated: true
note that autogenerated will skip validation. This must never be used without read_only. Please recheck all properties

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudnode.spec
> +    autogenerated: true
same

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudnode.spec
> +  - name: type
required or default_value

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudpolicy.spec
> +  - name: prismaCloudPolicyID
mostly readonly

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudpolicy.spec
> +  - name: severity
required or default_value

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudsubnet.spec
> +    - $filtering
not useful

2021-03-23 16:09 UTC, primalmotion commented on specs/cloudvpc.spec
> +    - $filtering
not useful

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +    - $filtering
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +    description: Deletes a cloud attachment.
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELEET /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  update:
this has no meaning for elemental . you can't do `UPDATE /xxx`

2021-03-23 16:09 UTC, primalmotion commented on specs/root.spec
> +  delete:
this has no meaning for elemental . you can't do `DELETE /xxx`

2021-03-23 16:53 UTC, dstiliadis commented on specs/+cloudendpointdata.spec
> +    default_value: true
my bad .. no need for default here.

2021-03-23 16:56 UTC, dstiliadis commented on specs/+cloudgraphnode.spec
> +  - name: type
This bothers me because we don't have an easy way of cross reference. This is essentially cloudnodetype,
but I can't find a way to reference that particular type in the spec. So I took the lazy way out and made it a string.

2021-03-23 16:58 UTC, dstiliadis commented on specs/+cloudgraphnodeaction.spec
> +  - name: action
Same problem with cross-reference and creating multiple types.

2021-03-23 17:07 UTC, dstiliadis commented on specs/+cloudnetworkrulesetdata.spec
> +  - name: subject
I need a new one. We assume tags are key=value. Will do.

2021-03-23 17:07 UTC, dstiliadis commented on specs/+cloudnetworkrulesetdata.spec
> +  - name: subject
I need a new one. We assume tags are key=value. Will do.

2021-03-23 17:08 UTC, dstiliadis commented on specs/+cloudroutedata.spec
> +    stored: true
a refList does pointer by default .. no ?

2021-03-23 17:10 UTC, dstiliadis commented on specs/+networkrule.spec
> +  - name: priority
Oh .. shoot .. this should have been reversed. My bad.

2021-03-23 17:13 UTC, dstiliadis commented on specs/+networkrule.spec
> +    default_value: 0
reversed to master .. bad check in

2021-03-23 17:14 UTC, dstiliadis commented on specs/@prismabase.abs
> +  - name: cloudType
Will do .. need to clean up this with the libraries.

2021-03-23 17:16 UTC, dstiliadis commented on specs/cloudalert.spec
> +    - $filtering
I wonder, where did I cut and paste this from :)

2021-03-23 17:18 UTC, dstiliadis commented on specs/cloudmanagednetwork.spec
> +    - $propagatable
yes .. this is tenant wide and it applies. to all children. Unless if I don't understand it right.

2021-03-23 17:23 UTC, dstiliadis commented on specs/cloudnetworkquery.spec
> +  - name: type
it has default_value

2021-03-23 17:24 UTC, dstiliadis commented on specs/cloudnetworkquerydestination.spec
> +  - name: type
read_only/auto-generated.

2021-03-23 17:25 UTC, dstiliadis commented on specs/cloudnode.spec
> +    - $filtering
no .. only read.. I removed the others.

2021-03-23 17:26 UTC, dstiliadis commented on specs/cloudnode.spec
> +- - namespace
ok .. Still optimizing this.

2021-03-23 17:27 UTC, dstiliadis commented on specs/cloudnode.spec
> +    subtype: map[string]interface{}
This is the key in all the conversions and data types. So that I don't store parameters for each object in different fields. Check the converters code in Yeul.

2021-03-23 17:27 UTC, dstiliadis commented on specs/cloudnode.spec
> +  - name: relatedObjectID
The whole object is readonly now. Do I even need to make the attributes read only?

2021-03-23 17:29 UTC, dstiliadis commented on specs/cloudnode.spec
> +    autogenerated: true
Note, that this is an internal proxy object. you cannot write it directly.

2021-03-23 17:30 UTC, dstiliadis commented on specs/cloudpolicy.spec
> +  - name: prismaCloudPolicyID
this comes from PC .. it is not read only.

2021-03-23 20:00 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "11fae9654b7eb1608a51497ec20f8e894539d029",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "e043cad87c65b8431b1f2e5eb83c7eda3bf6285d",
    "pipeline": "master"
  }
]
```

2021-03-23 20:17 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "11fae9654b7eb1608a51497ec20f8e894539d029",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "4bfa1ab7c7426d5d70bded278f1ecc1c1a9e6311",
    "pipeline": "master"
  }
]
```

2021-03-23 20:26 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "11fae9654b7eb1608a51497ec20f8e894539d029",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "75b211fe00a52351cf53dab488bfb0b6ed41c8f7",
    "pipeline": "master"
  }
]
```

2021-03-23 20:39 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "11fae9654b7eb1608a51497ec20f8e894539d029",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c6ec2b0c07edef1395a15b61d9a101031733ecf7",
    "pipeline": "master"
  }
]
```

2021-03-23 20:50 UTC, primalmotion requested changes

2021-03-23 20:50 UTC, primalmotion commented on specs/+cloudgraphnode.spec
> +  - name: type
you could make a type mapping for this... but if it's readonly (which is not) I guess it could be fine

2021-03-23 20:50 UTC, primalmotion commented on specs/+cloudnetworkrule.spec
> +    orderable: true
we need to use the tagexpression validation here

2021-03-23 20:50 UTC, primalmotion commented on specs/+cloudroutedata.spec
> +    stored: true
I don't remember maybe. please confirm

2021-03-23 20:50 UTC, primalmotion commented on specs/@prismabase.abs
> +# Attributes
not resolved yet

2021-03-23 20:50 UTC, primalmotion commented on specs/cloudalert.spec
> +  - name: cloudpolicies
`cloudPolicies`

2021-03-23 20:50 UTC, primalmotion commented on specs/cloudnode.spec
> +- - namespace
problem is that caitsith will not clean up indexes that have been rempoved, so to make efficient test, you should drop all these indexes everytime before testing. Also once it's gone outside, it's more complicated to manage

2021-03-23 20:50 UTC, primalmotion commented on specs/cloudnode.spec
> +  - name: relatedObjectID
yes, because if it moves later, and becomes accessible with an api route, then we're in trouble. all props of readonly object should be marked as read only. Since a ro object does not really exists, this is just based on trust in the code, and it'll likely come back and bit us (this already happened several times)

2021-03-23 20:50 UTC, primalmotion commented on specs/cloudpolicy.spec
> +  - name: prismaCloudPolicyID
then mostly creation_only.

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  update:
well it's still here :)

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  update:
still here

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  delete:
still here

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  update:
still here

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +    description: Deletes a cloud attachment.
still here

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  delete:
no update or delete

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  update:
still hjere

2021-03-23 20:50 UTC, primalmotion commented on specs/root.spec
> +  delete:
still here

2021-03-23 20:59 UTC, dstiliadis commented on specs/+cloudgraphnode.spec
> +  - name: type
The whole object is read only. (List of GraphNodes is read only). Doesn't this apply?

2021-03-23 21:02 UTC, dstiliadis commented on specs/@prismabase.abs
> +# Attributes
This is inherited mostly by proxy APIs. Is it better to add indexes here or in the actual API (ie cloudnode has the right indexes). May be there is 2 more than are missing in the users.

2021-03-23 21:05 UTC, dstiliadis commented on specs/cloudpolicy.spec
> +  - name: prismaCloudPolicyID
It will end up being an upsert .. the object has an ID .. I don't think we need to care about it.

2021-03-23 21:05 UTC, dstiliadis commented on specs/root.spec
> +  delete:
I can do update/delete of this API. Why no?

2021-03-24 00:34 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "335692aff11551b6d0b044be3ca28ff724ce7a75",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "b313bc25cfdeb01165f77004d97dae38c0664d7a",
    "pipeline": "master"
  }
]
```

2021-03-24 01:55 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "d2ca3b3444d1a4f7110096c162f13d038b6b17fb",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "335692aff11551b6d0b044be3ca28ff724ce7a75",
    "pipeline": "master"
  }
]
```

2021-03-24 02:38 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "7127993adb2ac09940da8be37872d8c5831b385f",
    "pipeline": "master"
  }
]
```

2021-03-24 03:13 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "a34a5af15ba84ede15de1f43a894ebd43ef587e9",
    "pipeline": "master"
  }
]
```

2021-03-24 05:16 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "3c3fc3e77a4eb97f957c69fecacf49f115124636",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "237e718b11ec2d063533f1ab963e2a286bac8515",
    "pipeline": "master"
  }
]
```

2021-03-24 19:31 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "0b98d152918f8745d9b6399b23822b3738b581fb",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f5785f6468722cbc7eb5ad631368a2a79a65d9b8",
    "pipeline": "master"
  }
]
```

2021-03-24 19:37 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "1612a899af401c469e4f9730309d0feb0eaa06e6",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "0b98d152918f8745d9b6399b23822b3738b581fb",
    "pipeline": "master"
  }
]
```

2021-03-24 21:28 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c05e7d6c974f2b8d3eea61d4e25ce43d47920d62",
    "pipeline": "master"
  }
]
```

2021-03-24 21:42 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c05e7d6c974f2b8d3eea61d4e25ce43d47920d62",
    "pipeline": "master"
  }
]
```

2021-03-24 22:02 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "b2d1f5daf0fe0ba7c3b72236469b5a69a76ec622",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  }
]
```

2021-03-24 23:36 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "18877570ec3938aec4255e529fd92b7dfa193ef3",
    "pipeline": "master"
  }
]
```

2021-03-24 23:40 UTC, dstiliadis commented on specs/@prismabase.abs
> +# Attributes
Indexes added to individual objects as per their use. Avoid carrying over data to proxy APIs that don't matter.

2021-03-24 23:40 UTC, dstiliadis commented on specs/root.spec
> +  delete:
fixed.

2021-03-24 23:55 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "18877570ec3938aec4255e529fd92b7dfa193ef3",
    "pipeline": "master"
  }
]
```

2021-03-25 00:04 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "3af5d80083f9ba61a51dd37b18c302b36251dc97",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "7ce71704588327d7ef60ffb5f2b8481262e1b88d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "18877570ec3938aec4255e529fd92b7dfa193ef3",
    "pipeline": "master"
  }
]
```

2021-03-25 00:10 UTC, dstiliadis commented on specs/+cloudnetworkrulesetdata.spec
> +  - name: subject
done

2021-03-25 00:34 UTC, dstiliadis commented on specs/cloudnetworkquery.spec
> +    stored: true
fixed.

2021-03-25 01:26 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "44648cf3bde48c577e4860e889d044029e01aa9e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f18c08953dff17d723b1f5ebca377d004da05cc5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "18877570ec3938aec4255e529fd92b7dfa193ef3",
    "pipeline": "master"
  }
]
```

2021-03-25 05:43 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "44648cf3bde48c577e4860e889d044029e01aa9e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f18c08953dff17d723b1f5ebca377d004da05cc5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c01f2c2f6376fc5f4749ac38c0c02a1d2a0c1151",
    "pipeline": "master"
  }
]
```

2021-03-25 05:49 UTC, dstiliadis commented on specs/@prismabase.abs
> +  - name: cloudType
We need to do this as a different PR. Currently the prismacloud lib, gaia, and backend have 3 different definitions of cloudtype (actually backend by itself has 2 - one in Karl and one in Pandemona). This needs to be consolidated with one central type or we will loose control.

2021-03-25 06:24 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "8dd393402da71022754bd0070f1d833e1f6db38e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f18c08953dff17d723b1f5ebca377d004da05cc5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c01f2c2f6376fc5f4749ac38c0c02a1d2a0c1151",
    "pipeline": "master"
  }
]
```

2021-03-25 15:42 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f18c08953dff17d723b1f5ebca377d004da05cc5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "b0785ad08b2a76b0dcece61842d00238c23490dc",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "8dd393402da71022754bd0070f1d833e1f6db38e",
    "pipeline": "master"
  }
]
```

2021-03-25 16:11 UTC, primalmotion approved these changes
LGTM

2021-03-25 16:42 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "8dd393402da71022754bd0070f1d833e1f6db38e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f18c08953dff17d723b1f5ebca377d004da05cc5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "dcf84a188a65882bd6252de2395263698e70dc7f",
    "pipeline": "master"
  }
]
```

2021-03-25 17:05 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "5a2ce4691b02ef6f47a79c46cff7c18a289d9699",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "4e0ece271fc37239a9032806cb287b9c442d3f13",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "4803f3aec312f61a88b768c8946abb770bc08c2b",
    "pipeline": "master"
  }
]
```

2021-03-26 04:45 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6b59d3f600adbb7fa670bfa4dc319a59512603e4",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f6811d56eabc7005e438ac76a25f851a54c8a891",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "c8c284d31e3bbe176c1294335d0b5fdeebc11abe",
    "pipeline": "master"
  }
]
```

2021-03-26 05:02 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "6b59d3f600adbb7fa670bfa4dc319a59512603e4",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f6811d56eabc7005e438ac76a25f851a54c8a891",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "23addf0f8d272ce4f6faaa35afed34ec8907f52a",
    "pipeline": "master"
  }
]
```

2021-03-26 05:21 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "dd5deeea63d485221db8f65e2a1e538e881f5d73",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "f6811d56eabc7005e438ac76a25f851a54c8a891",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "5c35519a9639c00e2c23ad66dfb84c02a9f205c2",
    "pipeline": "master"
  }
]
```

2021-03-26 06:22 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "d1c31b8bba476499df7af3ab607f467fac342a14",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "5e27d402fd95602d94757343a313c0445b94fb4b",
    "pipeline": "master"
  }
]
```

2021-03-26 06:26 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "d1c31b8bba476499df7af3ab607f467fac342a14",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "4a035ce868867666d31409fbbfe18e7b2373a985",
    "pipeline": "master"
  }
]
```

2021-03-26 07:07 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "6dedbfe7c2cbcd4c20772f331cce3e290842c826",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "d1c31b8bba476499df7af3ab607f467fac342a14",
    "pipeline": "master"
  }
]
```

2021-03-26 07:20 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "d1c31b8bba476499df7af3ab607f467fac342a14",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "1233d5a2222d7d440568c2ffd89606ed8973609e",
    "pipeline": "master"
  }
]
```

2021-03-26 07:23 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f0b2fe2115374970d04ed222783057480ebef1e2",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "d1c31b8bba476499df7af3ab607f467fac342a14",
    "pipeline": "master"
  }
]
```

2021-03-26 18:00 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "0069b216851eb3a3978937f716ddec51154ec7d8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "efd4cf7cfb6239a314e355186b97268dc9ae6136",
    "pipeline": "master"
  }
]
```

2021-03-26 18:01 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "0069b216851eb3a3978937f716ddec51154ec7d8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "670d75dfa4cb7382824c7f88f7db05cd6cc09bc3",
    "pipeline": "master"
  }
]
```

2021-03-26 18:14 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "0069b216851eb3a3978937f716ddec51154ec7d8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5d775d341a9b4803e657feb973999b170dade7f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f4917825b942c1fa70f8e5651596711d48a3b8b2",
    "pipeline": "master"
  }
]
```

2021-03-26 18:48 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "bdf1eff85063db71552b963731c303766f6bc7dd",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "a4b2418003334fa6ddb4ea71984b710f9413107d",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f4917825b942c1fa70f8e5651596711d48a3b8b2",
    "pipeline": "master"
  }
]
```

2021-03-26 18:55 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "6c681a314558ad3355e38fd2f14d4d0f458e66c1",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f4917825b942c1fa70f8e5651596711d48a3b8b2",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "bdf1eff85063db71552b963731c303766f6bc7dd",
    "pipeline": "master"
  }
]
```

2021-03-26 19:22 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "bdf1eff85063db71552b963731c303766f6bc7dd",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "70e9411f1d4e586a5c802c9762a3aa0c45091c24",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "f4917825b942c1fa70f8e5651596711d48a3b8b2",
    "pipeline": "master"
  }
]
```

2021-03-26 21:14 UTC, t00f requested changes
A few question and feedback on the validations especially.

2021-03-26 21:14 UTC, t00f commented on specs/cloudnode.spec
> +  - name: relatedObjectID
Should we have readonly attributes or not?

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +func ValidateCloudTag(attribute string, tag string) error {
I don't see the difference between `ValidateTagsExpresion` and `ValidateCloudTagsExpression`. This method seems similar to `ValidateTag` except `len([]byte(tag)) >= 512` is equal to `len([]byte(tag)) >= 1024`

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +		return makeValidationError(attribute, fmt.Sprintf("'%s' must be less than 1024 bytes", tag))
Actually the error message is still 1024 bytes here. Why is the restrictions different? If there are no differences, we could potentially reuse `ValidateTagsExpression`

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +func ValidateCIDRorIP(attribute string, network string) error {
`CIDRorIP` should be written everywhere `CIDROrIP`

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +		return makeValidationError(attribute, fmt.Sprintf("'%s' must be less than 1024 bytes", tag))
Error message not consistent with the check here

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +		if err := ValidateCloudNetworkQueryFilter("Entity CloudNetworkQuery", q.SourceSelector); err != nil {
the `attribute` (first parameter) should be the name of the property on the `CloudNetworkQuery`. Otherwise, the UI won't know on which attribute the error should be presented.

In that case, it should be `sourceSelector` instead of `Entity CloudNetworkQuery`

2021-03-26 21:14 UTC, t00f commented on custom_validations.go
> +		if err := ValidateCloudNetworkQueryFilter("Entity CloudNetworkQuery", q.DestinationSelector); err != nil {
In that case, it should be `destinationSelector` instead of `Entity CloudNetworkQuery`

2021-03-26 22:01 UTC, dstiliadis commented on custom_validations.go
> +		return makeValidationError(attribute, fmt.Sprintf("'%s' must be less than 1024 bytes", tag))
arg. Restrictions are different. I will change the message. Unlike the other tags, there is no "=" required on those. Just strings. And I thought that 1024 is an overkill.

2021-03-26 22:01 UTC, dstiliadis commented on custom_validations.go
> +func ValidateCloudTag(attribute string, tag string) error {
Look at the regular expression :)

2021-03-26 22:04 UTC, dstiliadis commented on custom_validations.go
> +		return makeValidationError(attribute, fmt.Sprintf("'%s' must be less than 1024 bytes", tag))
fixed.

2021-03-26 22:05 UTC, dstiliadis commented on custom_validations.go
> +		if err := ValidateCloudNetworkQueryFilter("Entity CloudNetworkQuery", q.SourceSelector); err != nil {
fixed.

2021-03-26 22:05 UTC, dstiliadis commented on custom_validations.go
> +		if err := ValidateCloudNetworkQueryFilter("Entity CloudNetworkQuery", q.DestinationSelector); err != nil {
fixed.

2021-03-26 22:07 UTC, dstiliadis commented
@t00f it doesn't let me report above. The whole cloudnode object is read only. It doesn't make any difference what the individual attributes are.

2021-03-26 22:14 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "5578180220d0a61761c8c57b584dbc146536c76e",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "2a85b2282acb808789261a8060794c98d49ba0d2",
    "pipeline": "master"
  }
]
```

2021-03-29 18:04 UTC, primalmotion commented on specs/@prismabase.abs
> +# Attributes
I don't understand. If the spec that inherits these properties are not behaving exactly the same, then this abstract certainly need to be split

2021-03-29 18:19 UTC, primalmotion requested changes

2021-03-29 18:19 UTC, primalmotion commented on specs/@prismabase.abs
> +# Attributes
after more discussion, agreement is that index declaration should move here

2021-03-29 18:36 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "dcddd6e586a5b71a95e1e2796993293e3a416abd",
    "pipeline": "master"
  }
]
```

2021-03-29 18:37 UTC, primalmotion approved these changes

2021-03-29 20:19 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "45e6727828d7cb44d58d59253b0405256ab6f2ef",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  }
]
```

2021-03-29 20:39 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "398deda46784a999035c9d2323f97e381d7e64e5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  }
]
```

2021-03-29 20:59 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "d7ad01d44fff8fed0dfc28e6f0c9efc2bd64d1e1",
    "pipeline": "master"
  }
]
```

2021-03-29 21:16 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "84b93335159e51850f3336b24be0dec4ba97feb0",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "d7ad01d44fff8fed0dfc28e6f0c9efc2bd64d1e1",
    "pipeline": "master"
  }
]
```

2021-03-29 21:55 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "net-effective",
    "component": "prismacloud",
    "pr-id": "13",
    "commit-sha": "460d108b3121106b21b37f580b61fda0cf05bff8",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "gaia",
    "pr-id": "603",
    "commit-sha": "cf29b41ea7fbad61855d5c2a685e0791649957f5",
    "pipeline": "master"
  },
  {
    "project": "net-effective",
    "component": "backend",
    "pr-id": "1003",
    "commit-sha": "e0cf90db430d968b5e9946112c3ae0d64561af99",
    "pipeline": "master"
  }
]
```

2021-03-30 00:13 UTC, t00f approved these changes

2021-03-30 00:17 UTC, merged

2021-04-06 19:11 UTC, emanic commented
Hi @dstiliadis in this PR we have a relative link to `cloudgraphedge`. However, this link does not resolve. Nowhere is `cloudgraphedge` defined. I think we may need that definition to be added, then we have no more broken link (plus we have this info) cc @t00f @primalmotion