New detected host mode container property on enforcer
PaloAltoNetworks/gaia pull request #623
Opened 2021-03-18 23:46 UTC by amitlimaye

Added a new property on the enforcer object to be set when we detect host mode 
containers that the enforcer is not going to enforce (ignore)

----

#

2021-03-19 00:46 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "2d42282568c76def9a57efc3da363afb92968d00",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "0bbe04c3a7694b2163221cb2d7ccb5e6cfa4c57b",
    "pipeline": "master"
  }
]
```

2021-03-19 21:16 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "b40c998fcb0b52e2efc337a4998f7f66776d2122",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "0bbe04c3a7694b2163221cb2d7ccb5e6cfa4c57b",
    "pipeline": "master"
  }
]
```

2021-03-19 22:07 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "b40c998fcb0b52e2efc337a4998f7f66776d2122",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "0bbe04c3a7694b2163221cb2d7ccb5e6cfa4c57b",
    "pipeline": "master"
  }
]
```

2021-03-19 22:33 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "b40c998fcb0b52e2efc337a4998f7f66776d2122",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "0bbe04c3a7694b2163221cb2d7ccb5e6cfa4c57b",
    "pipeline": "master"
  }
]
```

2021-03-19 22:39 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "b40c998fcb0b52e2efc337a4998f7f66776d2122",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "0bbe04c3a7694b2163221cb2d7ccb5e6cfa4c57b",
    "pipeline": "master"
  }
]
```

2021-03-22 20:07 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "b40c998fcb0b52e2efc337a4998f7f66776d2122",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "51a05f65ef22850d6db462f948d1e21aac964385",
    "pipeline": "master"
  }
]
```

2021-03-22 20:13 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "7c738ab5a4038163d65509e2592b98b041b79f43",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "51a05f65ef22850d6db462f948d1e21aac964385",
    "pipeline": "master"
  }
]
```

2021-03-22 20:22 UTC, primalmotion requested changes

2021-03-22 20:22 UTC, primalmotion commented on specs/enforcer.spec
> +      This field indicate whether the enforcer has detected host mode containers.
Indicates

2021-03-22 20:22 UTC, primalmotion commented on specs/enforcer.spec
> +    autogenerated: true
This cannot be autogenerated or transient

2021-03-22 20:22 UTC, primalmotion commented on specs/enforcer.spec
> +  - name: detectedHostModeContainer
should be plural

2021-03-22 21:27 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "7c738ab5a4038163d65509e2592b98b041b79f43",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "2df665229d1acb7bc802ae970818c4d45eee1c16",
    "pipeline": "master"
  }
]
```

2021-03-23 17:34 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "ec56641c9c0097808a2df989b43141839986a650",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "2df665229d1acb7bc802ae970818c4d45eee1c16",
    "pipeline": "master"
  }
]
```

2021-03-23 17:43 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "99fb5dd35eb90e65e7ca117d3d552dc203596f36",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "2df665229d1acb7bc802ae970818c4d45eee1c16",
    "pipeline": "master"
  }
]
```

2021-03-23 23:48 UTC, primalmotion requested changes
looks ok, but it's not correctly formatted

2021-03-23 23:48 UTC, primalmotion commented on specs/enforcer.spec
> +        description: If set, changes the enforcement status of the enforcer along with the poke.
There's a lot of unecessary changes here. you should need to use the `rego format` command if you are not using the vscode extension

2021-03-24 07:03 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "99fb5dd35eb90e65e7ca117d3d552dc203596f36",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-24 19:55 UTC, Rohit4793 approved these changes

2021-03-25 15:59 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "1d6180aa85a3c7a50227c875a39fc5cd53eb03ae",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-25 16:09 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "1d6180aa85a3c7a50227c875a39fc5cd53eb03ae",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-25 16:27 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "44f248d7c3159a00574320da203582a94f0bef37",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-25 16:40 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "3ff9080d0f8566110c406d02463f24a603acc689",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-25 16:56 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "3e17d26675a9aeee8aff20806329b92b099e8eda",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b577903d807026f444e56ed31e2b6a1c1031e672",
    "pipeline": "master"
  }
]
```

2021-03-25 17:50 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "3e17d26675a9aeee8aff20806329b92b099e8eda",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "b32f0ae12db3377037eec8e3209b1d39b46a5f06",
    "pipeline": "master"
  }
]
```

2021-03-25 17:52 UTC, t00f approved these changes
LGTM

2021-03-25 17:57 UTC, amitlimaye commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2311",
    "commit-sha": "3e17d26675a9aeee8aff20806329b92b099e8eda",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "623",
    "commit-sha": "af0cfa0751fc14e32bf8c74d2dfa7d5f1eee94d1",
    "pipeline": "master"
  }
]
```

2021-03-25 18:02 UTC, ericrpowers submitted a review, later dismissed

2021-03-25 18:35 UTC, primalmotion submitted a review, later dismissed

2021-03-25 21:25 UTC, primalmotion approved these changes

2021-03-25 21:33 UTC, merged