Update the results, fix validations, and add omit empty
PaloAltoNetworks/gaia pull request #627
Opened 2021-03-31 23:32 UTC by dstiliadis

## Description

Fixes several issues in cloud graph:

1. Update validations to match all the protocols from AWS and fix bugs there.
2. Update validations and change the notations around native IDs.
3. Add omit empty in objects in the results so that we reduce bandwidth
4. Add indexes for optimization.

2021-04-01 19:12 UTC, primalmotion requested changes

2021-04-01 19:12 UTC, primalmotion commented on specs/cloudnode.spec
> +- - namespace
This is unnecessary. The following index covers this one

2021-04-01 23:10 UTC, dstiliadis commented on specs/cloudnode.spec
> +- - namespace
Please check the new indexes. This is what gave the best performance.

2021-04-05 15:51 UTC, primalmotion approved these changes

2021-04-05 22:10 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graph-v2",
    "component": "gaia",
    "pr-id": "627",
    "commit-sha": "5aadc409fb7d8b427429df09266f50d5d5cf39c7",
    "pipeline": "master"
  },
  {
    "project": "graph-v2",
    "component": "backend",
    "pr-id": "1103",
    "commit-sha": "e8b213295fb14e6109a738e7fd894186963d8a60",
    "pipeline": "master"
  }
]
```

2021-04-05 22:19 UTC, dstiliadis commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graph-v2",
    "component": "gaia",
    "pr-id": "627",
    "commit-sha": "5aadc409fb7d8b427429df09266f50d5d5cf39c7",
    "pipeline": "master"
  },
  {
    "project": "graph-v2",
    "component": "backend",
    "pr-id": "1103",
    "commit-sha": "48aaf9c5ddff18ec7966a2cbf1927edf68d16cef",
    "pipeline": "master"
  }
]
```

2021-04-06 16:01 UTC, primalmotion approved these changes

2021-04-06 16:08 UTC, merged