Gaia model for vargid service.
PaloAltoNetworks/gaia pull request #631
Opened 2021-04-07 05:00 UTC by rramalinga

## Description

Vargid service is the policy enforcer for the Network Effective Permissions. Creating objects to track Alert Rules/Policy and Alert Rule Results.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2021-04-07 20:05 UTC, dstiliadis commented on specs/cloudalertrulecnq.spec
> +model:
What is this object doing? Why do we need API for this?

2021-04-07 20:06 UTC, dstiliadis commented on specs/cloudalertrulecnq.spec
> +model:
What is this object doing? Why do we need API for this? Is that for yeul to post the result? If yes, it doesn't need get and update/delete .. Can you explain?

2021-04-07 20:07 UTC, dstiliadis commented on specs/cloudalertrule.spec
> +  - '@named'
Does not need @named , @described but it needs @timeable

2021-04-07 20:08 UTC, dstiliadis commented on specs/cloudalertrule.spec
> +    description: List of accounts associated to alert rule.
I would change that to targetAccountIDs

2021-04-07 20:09 UTC, dstiliadis commented on specs/cloudalertrule.spec
> +    description: Prisma Cloud Alert Rule id.
alertRuleID

2021-04-07 20:09 UTC, dstiliadis commented on specs/cloudalertrule.spec
> +  - name: policyids
policyIDs

2021-04-07 20:09 UTC, dstiliadis commented on specs/cloudalertrulecnq.spec
> +model:
We cannot store the results of the queries. They are too big.

2021-04-07 20:10 UTC, dstiliadis requested changes
Please see inline.

2021-04-07 21:20 UTC, rramalinga commented on specs/cloudalertrulecnq.spec
> +model:
This is the POST API that yeul would call so that we get the results back for every CNQ that is scheduled.

2021-04-07 21:30 UTC, rramalinga commented on specs/cloudalertrule.spec
> +  - '@named'
My bad. Need to understand the semantics. Will fix this.

2021-04-09 23:01 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +      bson_name: ag
Remove this extension here.

2021-04-09 23:02 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +    description: Result of the last successfully run query.
Description copy is wrong. Something "The last time this query was executed".

2021-04-09 23:12 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +  rest_name: cloudalertrulecnq
I have some follow up questions:

1. Will you be using this model to also [store "derived" CNQs from the AlertRules you are ingesting](https://docs.google.com/document/d/1AD1gjz4ZTVu-lCR-m_wdTFq2nxh3xulwp1t7mF8NDz8/edit#heading=h.alg93knqtzrf)? I hope so as this will be required by the scheduler and we will need the "last exec timestamp" field to be indexed.

2. How come you need update and delete APIs as you can use the mongo manipulator directly within `vargid` to manage documents. AFAIK we only need one "POST" API for the Yeul workers.

2021-04-09 23:27 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +  rest_name: cloudalertrulecnq
Ah, I see you already responded to (2) in your response to a comment by @aporeto-dimitri. FYI for debugging you can just use the manipulator to retrieve the documents back instead of making an API call.

2021-04-09 23:28 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +  - policyid
Mmm...maybe to save two indexes we should just include the object ID of this model in the NATS message?

2021-04-09 23:29 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +  - policyid
Reference: [NATS message model](https://docs.google.com/document/d/1AD1gjz4ZTVu-lCR-m_wdTFq2nxh3xulwp1t7mF8NDz8/edit#heading=h.blzhub1juhlw)

2021-04-09 23:31 UTC, aaslamin commented on specs/cloudalertrulecnq.spec
> +  - resulttimestamp
Why is this a compound index?

2021-05-19 22:59 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "f3a381c61859dddbbbf388a1f3bb1e042360b63d",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "4780b4784c644b0c5ba82e2d96857711c20ee41d",
    "pipeline": "master"
  }
]
```

2021-05-20 20:16 UTC, t00f requested changes
Requires alignments in the naming

2021-05-20 20:16 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: Prisma Cloud Alert Rule id.
Is this property the identifier of the `CloudAlertRule` or is it the ID in PrismaCloud? 
I'm confused by the name and the description.

Please keep the same vocabulary everywhere. Right now we are using `Prisma Cloud Alert Rule` and `Alert Rule`.

2021-05-20 20:16 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: Alert rule description.
It seems we should go with `Alert rule` everywhere. So let's remove "Prisma Cloud Alert Rule" in favor of "Alert rule"

2021-05-20 20:16 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: Is Alert Rule enabled.
"Alert rule" -> Defines if the Alert rule is enabled.

2021-05-20 20:16 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: List of policy IDs associated to alert rule.
Here we are using lower case. 

Descriptions are used to generate the documentation. We need to be consistent.

2021-05-20 20:16 UTC, t00f commented on specs/cloudpolicy.spec
> +  - name: rqlQuery
Should be uppercase as it is an acryonym "RQLQuery"

2021-05-20 20:16 UTC, t00f commented on specs/cloudpolicy.spec
> +  - prismaCloudPolicyID
Yes, let's keep `prismaCloud` as a prefix when it references something coming from Prisma Cloud

2021-05-20 20:16 UTC, t00f commented on specs/cloudschedulednetworkquery.spec
> +    description: Prisma Cloud Policy ID.
Is it the PrismaCloud policy or the policy that is stored in CNS?

2021-05-20 23:26 UTC, rramalinga commented on specs/cloudschedulednetworkquery.spec
> +    description: Prisma Cloud Policy ID.
Changed the name to prismaCloudPolicyID for clarity

2021-05-20 23:26 UTC, rramalinga commented on specs/cloudpolicy.spec
> +  - prismaCloudPolicyID
Done

2021-05-21 07:01 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "f3a381c61859dddbbbf388a1f3bb1e042360b63d",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "6bfc1abc5ff318ac9ee6ac6fe0caf672692df813",
    "pipeline": "master"
  }
]
```

2021-05-21 17:52 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "aadf73204dc3bac8101e779545d1819ddb9b33f2",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "11c88e4dbe0c5c3455b611e0d3068671334f0050",
    "pipeline": "master"
  }
]
```

2021-05-21 18:02 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "aadf73204dc3bac8101e779545d1819ddb9b33f2",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "90791ceacd42380b3a1830098226497e608c8dc9",
    "pipeline": "master"
  }
]
```

2021-05-21 18:12 UTC, dstiliadis commented on specs/cloudalertrule.spec
> +    description: Is Alert Rule enabled.
let's use @described for the description and not a new attribute here.

2021-05-21 18:14 UTC, dstiliadis commented on specs/root.spec
> +
Let's use a better description here. This is the POST back of results if I am not wrong. This API needs to be marked as internal only also.

2021-06-11 23:29 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "dbe22d53356c0bb4e14b982800d5d7444e671664",
    "pipeline": "master"
  }
]
```

2021-06-11 23:39 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "dbe22d53356c0bb4e14b982800d5d7444e671664",
    "pipeline": "master"
  }
]
```

2021-06-11 23:46 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "821604d4594ce4df928342fdb579497a5f359055",
    "pipeline": "master"
  }
]
```

2021-06-12 02:17 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "311206aa3bb64ac3467d1266583d6f244896a5b4",
    "pipeline": "master"
  }
]
```

2021-06-15 01:19 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "f5ac7dc29fba8cdbdf73bfbc9aeca0cd7fff5007",
    "pipeline": "master"
  }
]
```

2021-06-15 17:18 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "42c0a17a77632bde8350b2ba486a9a02b0c4e135",
    "pipeline": "master"
  }
]
```

2021-06-17 23:38 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "dd2eeb7c76b5be188edcf99eb048b4366a1825a1",
    "pipeline": "master"
  }
]
```

2021-06-17 23:46 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "ef89f1878e119f6859ca837b05c87529e6fdcd32",
    "pipeline": "master"
  }
]
```

2021-06-18 00:15 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "20483ff77d4244d3ba705a30f6e0c5609bbe232f",
    "pipeline": "master"
  }
]
```

2021-06-18 21:49 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "08fa5aa20a86446ee29c21f5917d78444dccf0c8",
    "pipeline": "master"
  }
]
```

2021-06-18 22:47 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "c140e16cf5ab061ae69be4abc28a7893d3c5ad99",
    "pipeline": "master"
  }
]
```

2021-06-18 23:49 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "a31de52abda0b5894afae4142d401c40cd0ce17e",
    "pipeline": "master"
  }
]
```

2021-06-19 00:20 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "26aa4900e2ecaa7766cd245ce2fcd2edd8c98d62",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "a31de52abda0b5894afae4142d401c40cd0ce17e",
    "pipeline": "master"
  }
]
```

2021-06-19 00:32 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "a31de52abda0b5894afae4142d401c40cd0ce17e",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "427de263bb7036ba2b3b462d343006b2c34f4c3d",
    "pipeline": "master"
  }
]
```

2021-06-22 17:43 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: Is Alert Rule enabled.
+1

2021-06-22 17:43 UTC, t00f commented on specs/cloudalertrule.spec
> +    description: Is Alert Rule enabled.
+1

2021-06-22 19:12 UTC, t00f approved these changes

2021-06-22 19:20 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "9e566ab9882dd12d75354476afe19b4cef878aca",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "a31de52abda0b5894afae4142d401c40cd0ce17e",
    "pipeline": "master"
  }
]
```

2021-06-22 20:08 UTC, rramalinga commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vargid",
    "component": "gaia",
    "pr-id": "631",
    "commit-sha": "9e566ab9882dd12d75354476afe19b4cef878aca",
    "pipeline": "master"
  },
  {
    "project": "vargid",
    "component": "backend",
    "pr-id": "1149",
    "commit-sha": "a31de52abda0b5894afae4142d401c40cd0ce17e",
    "pipeline": "master"
  }
]
```

2021-06-23 21:14 UTC, merged