new: move api authorization policies to cid
PaloAltoNetworks/gaia pull request #654
Opened 2021-05-26 00:10 UTC by t00f

This PR is part of the first project to split the backend.

2021-06-02 16:28 UTC, primalmotion submitted a review, later dismissed

2021-06-02 16:28 UTC, primalmotion commented on specs/apiauthorizationpolicy.spec
> +  - '@zoned'
I guess you basically miss all other indexes

2021-06-02 16:39 UTC, primalmotion commented on specs/apiauthorizationpolicy.spec
> +  - '@identifiable-stored'
you should add propagated

2021-06-16 00:01 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "0bbf055835fe0ffc8b5fc8f9c88496890d441b66",
    "pipeline": "master"
  }
]
```

2021-06-16 03:59 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "e062a775ff487a9b4e7a76c329daa45c7d33d81a",
    "pipeline": "master"
  }
]
```

2021-06-16 04:23 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "45c4773d3a8bfc7b8e56ed3c73cd4f13f4b0725e",
    "pipeline": "master"
  }
]
```

2021-06-16 16:37 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "e3b4af8e974bdf8e83498f57d7cf96e5581473ed",
    "pipeline": "master"
  }
]
```

2021-06-16 16:49 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "7617e7c5badf301dde0d65f7baa4e1f360e03787",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  }
]
```

2021-06-16 17:36 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "8d76f5e3cb1193e85b3f0e2d56c333955ec9ee15",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  }
]
```

2021-06-16 18:47 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "6270d26d4874499a1ed31c49c235ed11bb49389d",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "d5fd476d10d31a1204f20bebe64efdebdf25b4ef",
    "pipeline": "master"
  }
]
```

2021-06-16 21:14 UTC, primalmotion requested changes

2021-06-16 21:14 UTC, primalmotion commented on specs/apiauthorizationpolicy.spec
> +- - namespace
you don't have a type here.

2021-06-16 21:14 UTC, primalmotion commented on specs/apiauthorizationpolicy.spec
> +  - name: propagate
should be readonly to make it clear

2021-06-17 23:13 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "f1eebc081bb5414b5be98c8a7bc963b4172d89e2",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "ab435de6fa4bddf180f77fa188acc72c1007c567",
    "pipeline": "master"
  }
]
```

2021-06-21 17:29 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "f1eebc081bb5414b5be98c8a7bc963b4172d89e2",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "dc031bfdbf24c54a0a73c01f75d1b9531cb01b0e",
    "pipeline": "master"
  }
]
```

2021-06-21 18:34 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "move_apiauth",
    "component": "gaia",
    "pr-id": "654",
    "commit-sha": "30ed8d50ae1cfdb934dbbf8438fbb2a9cc96be68",
    "pipeline": "master"
  },
  {
    "project": "move_apiauth",
    "component": "backend",
    "pr-id": "1193",
    "commit-sha": "bc5f2c5a2a4d3ab4c8bc1f6c1081e8ceeadb2d4f",
    "pipeline": "master"
  }
]
```

2021-06-22 19:01 UTC, merged