WIP: Add spec file for ServicePublication
PaloAltoNetworks/gaia pull request #662
Opened 2021-06-03 19:48 UTC by malkhamis-panw

TODO

2021-06-03 23:59 UTC, primalmotion requested changes

2021-06-03 23:59 UTC, primalmotion commented on specs/servicepublication.spec
> +  update:
you don't need this

2021-06-03 23:59 UTC, primalmotion commented on specs/root.spec
> +    description: TODO.
please write descriptions immediately. otherwise the TODO will end up in prod, that's almost a gurantee

2021-06-04 23:53 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "0bdd3d0a5966276c7ad2df36765bbc644312c459",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "1af7109b6114b4166a6df1f8eda38a62c73f5de8",
    "pipeline": "master"
  }
]
```

2021-06-04 23:59 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "1af7109b6114b4166a6df1f8eda38a62c73f5de8",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "0bdd3d0a5966276c7ad2df36765bbc644312c459",
    "pipeline": "master"
  }
]
```

2021-06-05 00:02 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "a85a71577b25ec77f4b492bffab322af0a9a5638",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "cde1351bbe12a73f7ae059906a1fbe28ccf20757",
    "pipeline": "master"
  }
]
```

2021-06-07 16:54 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "a85a71577b25ec77f4b492bffab322af0a9a5638",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "cde1351bbe12a73f7ae059906a1fbe28ccf20757",
    "pipeline": "master"
  }
]
```

2021-06-07 16:56 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "dced1f121d86488069e86b94d4a40bebb16b3f93",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "9433c623fd637567bece1175d60fc680125f2ac3",
    "pipeline": "master"
  }
]
```

2021-06-07 20:33 UTC, primalmotion commented on specs/servicepublication.spec
> +    exposed: true
This property should be required

2021-06-08 18:37 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "2f05c41ecf51918a1c5e9b45545a941df219ca1a",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "cb0274a92f7f823608006404f02a9bd70dcff000",
    "pipeline": "master"
  }
]
```

2021-06-08 20:05 UTC, primalmotion approved these changes

2021-06-11 20:15 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "3fc0957650287b10e20abdaa14462bc2a4972ea4",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "b62918f4d85ad8c3390174259409dab69773b934",
    "pipeline": "master"
  }
]
```

2021-06-14 22:19 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "b62918f4d85ad8c3390174259409dab69773b934",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "ed6abdf08753396abe67659eef4672c0f5c55636",
    "pipeline": "master"
  }
]
```

2021-06-14 23:03 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "571be1d8f4fe9e51238ff8200e895605f7d5cc89",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "b62918f4d85ad8c3390174259409dab69773b934",
    "pipeline": "master"
  }
]
```

2021-06-15 01:15 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "service-publication",
    "component": "backend",
    "pr-id": "1210",
    "commit-sha": "2ec89d3499e2a8601f32f1d03e0f008f11ac8a0b",
    "pipeline": "master"
  },
  {
    "project": "service-publication",
    "component": "gaia",
    "pr-id": "662",
    "commit-sha": "b62918f4d85ad8c3390174259409dab69773b934",
    "pipeline": "master"
  }
]
```

2021-06-15 18:11 UTC, merged