New: NamespaceInfo Proxy API
PaloAltoNetworks/gaia pull request #672
Opened 2021-06-18 22:55 UTC by ericrpowers

#### Description
There is interest to add more read-only access to a namespace's information, so instead of making a proxy API per attribute, we will create a new API called `/namespaceinfo` that we will use to house all the requested attributes. This will lead to `/namespacepolicyinfo` to be deprecated.

Values we want for now are:
- PU traffic actions
- Tag Prefixes
- Name
- Description
- Protected

2021-06-18 22:59 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "proxy-api-namespaceinfo",
    "component": "backend",
    "pr-id": "1251",
    "commit-sha": "4a7014a50d6b7aa35eb62c6f6603f20605f90668",
    "pipeline": "master"
  },
  {
    "project": "proxy-api-namespaceinfo",
    "component": "gaia",
    "pr-id": "672",
    "commit-sha": "855fe894f64e3dbd4a5d41524da97d544845d419",
    "pipeline": "master"
  }
]
```

2021-06-19 00:07 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "proxy-api-namespaceinfo",
    "component": "backend",
    "pr-id": "1251",
    "commit-sha": "06480329eb04f09db30e9c14298ee6ad728b9e84",
    "pipeline": "master"
  },
  {
    "project": "proxy-api-namespaceinfo",
    "component": "gaia",
    "pr-id": "672",
    "commit-sha": "855fe894f64e3dbd4a5d41524da97d544845d419",
    "pipeline": "master"
  }
]
```

2021-06-21 21:24 UTC, primalmotion requested changes

2021-06-21 21:24 UTC, primalmotion commented on specs/namespaceinfo.spec
> +  - name: protected
should be readonly

2021-06-28 18:07 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "proxy-api-namespaceinfo",
    "component": "gaia",
    "pr-id": "672",
    "commit-sha": "e6c8a9abfd90360a260f8ee7eb7a17d15dddd2e2",
    "pipeline": "master"
  },
  {
    "project": "proxy-api-namespaceinfo",
    "component": "backend",
    "pr-id": "1251",
    "commit-sha": "8591a166aac6419519edafe13c64f8a3a532a116",
    "pipeline": "master"
  }
]
```

2021-06-28 19:25 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "proxy-api-namespaceinfo",
    "component": "backend",
    "pr-id": "1251",
    "commit-sha": "34bb6a832ee83c80c4fba258c04c22082f4195fd",
    "pipeline": "master"
  },
  {
    "project": "proxy-api-namespaceinfo",
    "component": "gaia",
    "pr-id": "672",
    "commit-sha": "e6c8a9abfd90360a260f8ee7eb7a17d15dddd2e2",
    "pipeline": "master"
  }
]
```

2021-06-29 01:05 UTC, primalmotion approved these changes

2021-06-29 01:29 UTC, merged