Feature: openapi3
PaloAltoNetworks/gaia pull request #683
Opened 2021-07-07 23:27 UTC by malkhamis-panw

2021-07-12 16:52 UTC, primalmotion commented on specs/_type.mapping
> +  openapi3: # ignored
the presence of this comment seems to indicate you did not run make format

2021-07-12 16:52 UTC, primalmotion reviewed
make sure make format has been run

2021-08-17 18:57 UTC, primalmotion requested changes
lot's of mistakes and shortcuts in here

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks simplified

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
can't we make ref to a defined model here?

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
can't we make ref to a defined model here?

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
can't we make ref to a defined model here?

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
that looks incorrect

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
this probably need to be fully defined here

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
this probably need to be  fully defined here

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
this should be fully defined here

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
should be fully defined here

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
can't we make ref to a defined model here?

2021-08-17 18:57 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
can't we make ref to a defined model here?

2021-09-02 20:45 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
we said we ignore these outdated hacky objects

2021-09-02 20:45 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
we said we ignore these outdated hacky objects

2021-09-02 23:44 UTC, malkhamis-panw commented on specs/_type.mapping
> +        "type": "object"
I don't think so.. the `$ref` key there assumes that the referenced type is "hopefully" defined in the `#component/schemas` section of the final openapi3 doc

2021-09-02 23:44 UTC, malkhamis-panw commented on specs/_type.mapping
> +        "type": "object"
this response applies to other similar PR comments

2021-09-02 23:49 UTC, malkhamis-panw commented on specs/_type.mapping
> +        "type": "object"
I don't think so.. the `$ref` key there assumes that the referenced type is "hopefully" defined in the `#component/schemas` section of the final openapi3 doc rather than the `_type.mapping` file. Unless there is a trick I am not aware of. These types seem to be defined in gaia/types/*.go

2021-09-02 23:49 UTC, malkhamis-panw commented on specs/_type.mapping
> +        "type": "object"
I don't think so.. the `$ref` key there assumes that the referenced type is "hopefully" defined in the `#component/schemas` section of the final openapi3 doc rather than the `_type.mapping` file. Unless there is a trick I am not aware of. These types seem to be defined in gaia/types/*.go

2021-09-03 00:00 UTC, primalmotion commented on specs/_type.mapping
> +        "type": "object"
yep

2021-09-03 00:00 UTC, primalmotion approved these changes
This looks good as a base. Certainly a few details will need to be adapted along the way, but I think this is mergeable now

2021-09-03 00:03 UTC, merged