KubernetesCluster type
PaloAltoNetworks/gaia pull request #703
Opened 2021-09-07 23:01 UTC by philipatl

## Description

New `KubernetesCluster` type for use by our aggregated API server for Kubernetes.
https://redlock.atlassian.net/browse/CNS-2441

## Motivation and Context

Our aggregated API server for Kubernetes will create an instance of this type at time of installation.
It will be used also to request a DatapathCertificate for the aggregated API server to use.

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2021-09-07 23:09 UTC, philipatl commented
/build

2021-09-08 19:09 UTC, primalmotion requested changes

2021-09-08 19:09 UTC, primalmotion commented on specs/kubernetescluster.spec
> +  - name: annotations
we have a abs spec annotable. If you mean setting annotations from the clutser, I don't think we should. This contains uncontrolled data on the k8s side and I don't think we need them here.

We should however add *our* annotation attribute

2021-09-08 19:09 UTC, primalmotion commented on specs/kubernetescluster.spec
> +  - name: namespace
if you mean the k8s namespace, it must be name K8SNamespace, otherwise it will conflicts with our own namespace (that you missed)

2021-09-08 19:09 UTC, primalmotion commented on specs/kubernetescluster.spec
> +  - '@identifiable-stored'
we need
```
  - '@zoned'
  - '@migratable'
  - '@base'
  - '@namespaced'
  - '@described'
  - '@identifiable-stored'
  - '@metadatable'
  - '@named'
  - '@timeable'
```

2021-09-08 20:20 UTC, philipatl commented on specs/kubernetescluster.spec
> +  - name: annotations
I wanted our annotation attribute, but I didn't think we needed all of `@base` but it sounds like we do.

2021-09-08 21:32 UTC, primalmotion commented on specs/kubernetescluster.spec
> +  - name: annotations
ok so it's *not* to store k8s annotations, correct?

2021-09-08 21:35 UTC, philipatl commented on specs/kubernetescluster.spec
> +  - name: annotations
That is correct.

2021-09-08 21:55 UTC, primalmotion commented
ok let's leave this here. I'll work on the backend PR tomorrow to handle it

2021-09-10 19:52 UTC, merged