new: api server specific fields
PaloAltoNetworks/gaia pull request #706
Opened 2021-09-14 20:31 UTC by sibicramesh

Adding new fields specific to k8s api server

2021-09-14 21:17 UTC, primalmotion requested changes

2021-09-14 21:17 UTC, primalmotion commented on specs/kubernetescluster.spec
> +    description: It contains the fqdns that will be set in the certificate SANS field.
`Contains the FQDNs used by the API server. They will be used to populate the Certificate DNS SANs field`

2021-09-14 21:17 UTC, primalmotion commented on specs/kubernetescluster.spec
> +    description: It contains the ips that will be set in the certificate SANS field.
Contains the IPs used by the API server. They will be used to populate the Certificate IP SANs field

2021-09-14 21:17 UTC, primalmotion commented on specs/kubernetescluster.spec
> +    description: |-
if we want to impose a format, we must add a custom validation

2021-09-14 21:17 UTC, primalmotion commented on specs/kubernetescluster.spec
> +  - name: APIServerVersions
This probably needs a validation? I'm nor sure how an APIServer version looks like

2021-09-15 05:59 UTC, sibicramesh commented on specs/kubernetescluster.spec
> +  - name: APIServerVersions
The version can have different schemas, there is no definite format for it. Here is the doc https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

2021-09-15 12:12 UTC, philipatl approved these changes

2021-09-15 16:13 UTC, primalmotion requested changes
just a minor typo. otherwise LGTM

2021-09-15 16:13 UTC, primalmotion commented on custom_validations.go
> +		return makeValidationError(attribute, fmt.Sprintf("invalid service name, should be of format <service name>.<service snamespace>.svc: %s", serviceName))
snamespace

2021-09-15 16:18 UTC, philipatl submitted a review, later dismissed

2021-09-15 23:06 UTC, philipatl approved these changes

2021-09-16 17:55 UTC, merged