new: syslog config
PaloAltoNetworks/gaia pull request #738
Opened 2021-11-11 00:55 UTC by sibicramesh

https://redlock.atlassian.net/browse/CNS-3670

2021-11-12 20:11 UTC, t00f commented on specs/enforcerprofile.spec
> +  - name: syslogEnable
should be `syslogEnabled`

2021-11-12 20:11 UTC, t00f commented on specs/enforcerprofile.spec
> +    description: PEM-encoded certificate to expose to the clients for TLS.
Not sure I understand the description - is it the certificate that will allow the enforcer to connect to the syslog server? What do we expose to clients?

2021-11-12 20:11 UTC, t00f commented on specs/enforcerprofile.spec
> +    max_value: 23
How is the user giving this value? Is it ok to ask for an integer? If we are limited, maybe we can have more human readable options?

2021-11-12 20:11 UTC, t00f commented on specs/enforcerprofile.spec
> +  - name: syslogEndpointTLSServerCA
Ok I feel like we want to do MTLS between the syslog server and the enforcer, right?

2021-11-12 20:13 UTC, sibicramesh commented on specs/enforcerprofile.spec
> +  - name: syslogEndpointTLSServerCA
Correct.

2021-11-12 20:14 UTC, sibicramesh commented on specs/enforcerprofile.spec
> +    description: PEM-encoded certificate to expose to the clients for TLS.
We will be doing MTLS.

2021-11-12 20:15 UTC, sibicramesh commented on specs/enforcerprofile.spec
> +    max_value: 23
@mheese wanted to have all the facilities and give the users the ability to choose from any of them.

2021-11-12 21:43 UTC, primalmotion requested changes

2021-11-12 21:43 UTC, primalmotion commented on specs/enforcerprofile.spec
> +    encrypted: true
I believe this key needs to be sent to enforcer. We usually don't store private keys in a retrievable manner. This goes against the security posture of the backend.

2021-11-22 18:28 UTC, primalmotion approved these changes

2021-11-22 18:48 UTC, mheese approved these changes
has everything we need from our end 👍

2021-11-22 19:17 UTC, merged