Feature/cid: support multiple authorized namespaces
PaloAltoNetworks/gaia pull request #739
Opened 2021-11-13 01:08 UTC by malkhamis-panw

2021-11-13 01:29 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "64adca992ae71f663f926f49ed71a93f011ef7ec",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "d1062ce45a0a2708991f24240f2480990b14b24d",
    "pipeline": "master"
  }
]
```

2021-11-17 05:52 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "c618f42dac7c55f41f0a5be3cd0cde1a8237f673",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "301089c9ba9a27ba1d72e8a196481a2ee0e209dc",
    "pipeline": "master"
  }
]
```

2021-11-17 06:20 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "c618f42dac7c55f41f0a5be3cd0cde1a8237f673",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "b6f4b600c3689654ef417e0b545251b829594693",
    "pipeline": "master"
  }
]
```

2021-11-17 22:30 UTC, t00f submitted a review, later dismissed

2021-11-17 22:50 UTC, primalmotion requested changes

2021-11-17 22:50 UTC, primalmotion commented on specs/apiauthorizationpolicy.spec
> +  - name: authorizedNamespaces
make the old one not stored and not required. We don't want to maintain 2 list. Setting one in authorizedNamespaces should make the processor add it in authorizedNamespaces.

2021-11-18 01:54 UTC, malkhamis-panw commented on specs/apiauthorizationpolicy.spec
> +  - name: authorizedNamespaces
> Setting one in authorizedNamespaces should make the processor add it in authorizedNamespaces.

This is already taken care of in the processor..

2021-11-19 00:28 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "1955f041db69e8e3705f28877f8867864616a64c",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "8fd7d050e3963974826631979d1d0e08b73aa6ea",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "underwater",
    "pr-id": "182",
    "commit-sha": "393e8113da9966297205b3dd41f0939457aa040f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "apotests",
    "pr-id": "3549",
    "commit-sha": "4cb3ccb774e1ddfc0584adc006e8bfa09f08eade",
    "pipeline": "master"
  }
]
```

2021-11-19 06:43 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "c0e996d8e9d78891c313022fe95756c64f325d2f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "e7e9925270a58b329e1298d681e47f00ab3d9b65",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "underwater",
    "pr-id": "182",
    "commit-sha": "393e8113da9966297205b3dd41f0939457aa040f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "apotests",
    "pr-id": "3549",
    "commit-sha": "4cb3ccb774e1ddfc0584adc006e8bfa09f08eade",
    "pipeline": "master"
  }
]
```

2021-11-19 17:31 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "c0e996d8e9d78891c313022fe95756c64f325d2f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "b058df3b610dbcc902394a6ed3a2bb597510e1db",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "underwater",
    "pr-id": "182",
    "commit-sha": "393e8113da9966297205b3dd41f0939457aa040f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "apotests",
    "pr-id": "3549",
    "commit-sha": "4cb3ccb774e1ddfc0584adc006e8bfa09f08eade",
    "pipeline": "master"
  }
]
```

2021-11-19 18:33 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "gaia",
    "pr-id": "739",
    "commit-sha": "c0e996d8e9d78891c313022fe95756c64f325d2f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "backend",
    "pr-id": "1446",
    "commit-sha": "b058df3b610dbcc902394a6ed3a2bb597510e1db",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "underwater",
    "pr-id": "182",
    "commit-sha": "393e8113da9966297205b3dd41f0939457aa040f",
    "pipeline": "master"
  },
  {
    "project": "cid-multiple-authorized-namespaces",
    "component": "apotests",
    "pr-id": "3549",
    "commit-sha": "4cb3ccb774e1ddfc0584adc006e8bfa09f08eade",
    "pipeline": "master"
  }
]
```

2021-11-19 20:16 UTC, malkhamis-panw commented on specs/apiauthorizationpolicy.spec
> +  - name: authorizedNamespaces
> make the old one not stored

@primalmotion  It turned out we can't do that yet... Making `stored: false` will result in field `AuthorizedNamespace`  getting slapped with `bson:"-"`. This would make the field ignored when serializing for db storage AND deserializing from db. As a result, when we run the migration, we `AuthorizedNamespace` will always be read as an empty string and when we set it to the empty value, that will be ignored... When we ran the migration, we observed that the migration script did the following as a result of making the field not stored

```
{
  "AuthorizedNamespace":  "/old/value/still/here",
  "AuthorizedNamespaces" [ "" ]
}
```

2021-11-19 21:34 UTC, t00f approved these changes

2021-11-22 18:34 UTC, primalmotion approved these changes

2021-11-24 19:03 UTC, merged