Conditions and actions
PaloAltoNetworks/gaia pull request #740
Opened 2021-11-15 20:12 UTC by ericrpowers

#### Description
As we start to resurrect the automation work, we want to make things more modular. Instead of automation templates, we will not have automation conditions and automation actions. This will allow us to more easily define the individual components of an automation in the future.

2021-11-15 20:18 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "conditions-and-actions",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "cf52791bfe6716d7c17d2cc6558e9d02320949c0",
    "pipeline": "master"
  },
  {
    "project": "conditions-and-actions",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "21154f465241c08917e9889e55bc6498ed0ba9c6",
    "pipeline": "master"
  },
  {
    "project": "conditions-and-actions",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "bb35372b65973d00701b99f887a5ce28ada1b34c",
    "pipeline": "master"
  },
  {
    "project": "conditions-and-actions",
    "component": "cookbook",
    "pr-id": "38",
    "commit-sha": "cca6d1682a0fa9d2b039a51b2fd9e153b136007c",
    "pipeline": "master"
  }
]
```

2021-11-16 08:21 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "bb35372b65973d00701b99f887a5ce28ada1b34c",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3544",
    "commit-sha": "8536c617c077106ed6db0f694e1b188aa791bc52",
    "pipeline": "master"
  }
]
```

2021-11-16 17:26 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "bb35372b65973d00701b99f887a5ce28ada1b34c",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3544",
    "commit-sha": "47e108ff7aae1686790dbee4453f90713f8dd6e1",
    "pipeline": "master"
  }
]
```

2021-11-16 20:02 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "21154f465241c08917e9889e55bc6498ed0ba9c6",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "bb35372b65973d00701b99f887a5ce28ada1b34c",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "2b34b6dc6ca461c1cb1e7f03bdb278f7438af900",
    "pipeline": "master"
  }
]
```

2021-11-16 23:30 UTC, t00f commented on specs/automationaction.spec
> +    stored: true
I am wondering if we still need this `key`. If it is required, we probably need an index.
cc @primalmotion

2021-11-17 17:59 UTC, primalmotion requested changes

2021-11-17 17:59 UTC, primalmotion commented on specs/automationcondition.spec
> +
needs unique index on the (namespace,key)

2021-11-17 17:59 UTC, primalmotion commented on specs/automationaction.spec
> +  - '@timeable'
needs unique index on the (namespace,key)

2021-11-18 01:20 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "d84dec33d6412fd64c177e986d23272ec1723ac9",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 07:47 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "3fac91fe0119ba4d03b03d9ed492fef02290c00b",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 07:51 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "3fac91fe0119ba4d03b03d9ed492fef02290c00b",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 08:27 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "3fac91fe0119ba4d03b03d9ed492fef02290c00b",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 10:02 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "0d6207036c2ea9a90f7bcf094f883be813dcda7b",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 12:34 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "19415a8630ace44d2a9f8a795dddcb347ca9bacd",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 17:18 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "9ab764664c6a17bb1ed329cb225849f770bd14b3",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  }
]
```

2021-11-18 21:44 UTC, primalmotion approved these changes

2021-11-18 21:55 UTC, ericrpowers commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "underwater",
    "pr-id": "180",
    "commit-sha": "fa702beda2f2386d07196c5e1a9d6db80f811df8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "740",
    "commit-sha": "0ff921ec880a01b350f74a3b9446a9c5a90192d0",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1447",
    "commit-sha": "45e8c79473ac326424517c4a3c058e8947767135",
    "pipeline": "master"
  }
]
```

2021-11-19 00:07 UTC, merged