feature/jenova: include proto/port in suggested policies
PaloAltoNetworks/gaia pull request #747
Opened 2021-12-10 01:36 UTC by malkhamis-panw

Coming soon..

2021-12-10 01:47 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "6649fd6e03c4a4004f0b483519766ab172716c23",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "a2871b6d4f3c6e7fed6a507b138339f866282130",
    "pipeline": "master"
  }
]
```

2021-12-10 05:50 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "6649fd6e03c4a4004f0b483519766ab172716c23",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "3d588800c85b0972b9711d6bd2731ea19d8e28d4",
    "pipeline": "master"
  }
]
```

2021-12-14 00:19 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "6649fd6e03c4a4004f0b483519766ab172716c23",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "99a992d16129eb3d2a5cad2fba013cfc0ce66a74",
    "pipeline": "master"
  }
]
```

2021-12-14 01:12 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "6649fd6e03c4a4004f0b483519766ab172716c23",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "a94632ee489ba0d63227f7814b2ec49685abd59b",
    "pipeline": "master"
  }
]
```

2021-12-14 17:26 UTC, primalmotion requested changes
Also, I'm not sure why all the line limits changed here. you need to run rego format

2021-12-14 17:26 UTC, primalmotion commented on specs/+graphedgeflowdetails.spec
> +  - name: allowed
We usually use an enum here. In either way the terminology is `accept(ed)`/`reject(ed)`

2021-12-14 17:26 UTC, primalmotion commented on specs/graphedge.spec
> +    type: external
IIRC we have a type `refMap` that would prevent the need for a type mapping

2021-12-14 17:29 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "6649fd6e03c4a4004f0b483519766ab172716c23",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "259cbf116ee207e0a53543d68602b8f832a3ab22",
    "pipeline": "master"
  }
]
```

2021-12-14 20:39 UTC, malkhamis-panw commented on specs/graphedge.spec
> +    type: external
done

2021-12-14 20:39 UTC, malkhamis-panw commented on specs/+graphedgeflowdetails.spec
> +  - name: allowed
I kept it boolean for simplicity and inline with other `acceptedXX` fields in the parent spec. Changed it to `Accepted`

2021-12-14 20:40 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "e99cacf23fd94d05d4cf744e4f4bc1216fd49bce",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "6261dcd7d63b2b6bc23f92e4959ba98ce012cf30",
    "pipeline": "master"
  }
]
```

2021-12-14 20:57 UTC, primalmotion approved these changes

2021-12-14 20:58 UTC, malkhamis-panw commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "backend",
    "pr-id": "1472",
    "commit-sha": "a8a166c4d57ee3715d4aff891472667f092b262d",
    "pipeline": "master"
  },
  {
    "project": "feature-jeonva-suggested-policies-proto-port",
    "component": "gaia",
    "pr-id": "747",
    "commit-sha": "e99cacf23fd94d05d4cf744e4f4bc1216fd49bce",
    "pipeline": "master"
  }
]
```

2021-12-14 23:29 UTC, malkhamis-panw commented
FT is failing due to a known issue in enforcer per QA team. Suggestion was to force-merge MR for the time being

2021-12-14 23:29 UTC, merged