added enableAzurev1 to cnsconfig
PaloAltoNetworks/gaia pull request #788
Opened 2022-03-29 22:34 UTC by sawyerawesome

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2022-03-30 19:09 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "e2251f5c7ce368e2051c369abaf0b26f2b450ebc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "71a79dea8881f75233c43202c865265af237876d",
    "pipeline": "master"
  }
]
```

2022-03-30 22:26 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "e2251f5c7ce368e2051c369abaf0b26f2b450ebc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "520fe2e1ef083b6c82bfbafa7968f4e1d8fd843d",
    "pipeline": "master"
  }
]
```

2022-03-31 20:55 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "e2251f5c7ce368e2051c369abaf0b26f2b450ebc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "22a58ef342ea92f7b44a1d8664262709d26634f4",
    "pipeline": "master"
  }
]
```

2022-03-31 22:22 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "e2251f5c7ce368e2051c369abaf0b26f2b450ebc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "3e569e1fceadab96359e3fe0af55e0d2e59211f8",
    "pipeline": "master"
  }
]
```

2022-03-31 23:14 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "e2251f5c7ce368e2051c369abaf0b26f2b450ebc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "4130e8ee2255357be86d5880d121f36b90747278",
    "pipeline": "master"
  }
]
```

2022-03-31 23:39 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "a373f2df07ae58cf99907ce0be77f21b3afe1f8e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "4130e8ee2255357be86d5880d121f36b90747278",
    "pipeline": "master"
  }
]
```

2022-04-01 18:26 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "4130e8ee2255357be86d5880d121f36b90747278",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "3c50112d1e67bf94b8edfc636ddbcd8a2fe73d51",
    "pipeline": "master"
  }
]
```

2022-04-01 20:05 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "3c50112d1e67bf94b8edfc636ddbcd8a2fe73d51",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "4130e8ee2255357be86d5880d121f36b90747278",
    "pipeline": "master"
  }
]
```

2022-04-01 22:00 UTC, ericrpowers submitted a review, later dismissed
I am not sure of our standard with having v1, v2, v3... in an attribute (Should it be `enableAzurev1` or `enableAzureV1`). Considering this is a temporary measure anyway, LGTM

2022-04-01 23:05 UTC, primalmotion requested changes

2022-04-01 23:05 UTC, primalmotion commented on specs/cnsconfig.spec
> +  - name: enableAzurev1
`azureV1Enabled`. Booleans in api must be in the passive form

2022-04-01 23:06 UTC, primalmotion commented on specs/cnsconfig.spec
> +  - name: enableAzurev1
I realize there are other enableX on this api. if we can still change them, now is the time

2022-04-04 22:14 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "3c50112d1e67bf94b8edfc636ddbcd8a2fe73d51",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "495e5f7f1c4900eb0d7ddea64921664934307fd3",
    "pipeline": "master"
  }
]
```

2022-04-05 20:50 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "4b16f64b5d2f6ef0bc5d70f953c6e20968d52003",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "34a40befc747cec7d2f2f350f591f79d073d1a1a",
    "pipeline": "master"
  }
]
```

2022-04-05 21:11 UTC, sawyerawesome commented on specs/cnsconfig.spec
> +  - name: enableAzurev1
https://redlock.atlassian.net/browse/CNS-4883

2022-04-05 22:47 UTC, ericrpowers approved these changes

2022-04-05 23:52 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "4b16f64b5d2f6ef0bc5d70f953c6e20968d52003",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "e33dc664a752588df066037871c027cdba562fd2",
    "pipeline": "master"
  }
]
```

2022-04-06 18:13 UTC, sawyerawesome commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1631",
    "commit-sha": "4ed887c1cc98c6f6645f14fa11572346fd771972",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "788",
    "commit-sha": "4b16f64b5d2f6ef0bc5d70f953c6e20968d52003",
    "pipeline": "master"
  }
]
```

2022-04-06 18:55 UTC, merged