Adding alert fields for dynamic exposure related information
PaloAltoNetworks/gaia pull request #975
Opened 2024-09-09 22:28 UTC by knainwal

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2024-09-09 22:43 UTC, sawyerawesome commented on specs/+dynamicexposurealertpayload.spec
> +  - name: publicIP
this can also be fqdn? Or we will always report the IPs?

2024-09-09 22:47 UTC, sawyerawesome commented on specs/cloudalertrecord.spec
> +    subtype: integer
should be string here?

2024-09-09 22:47 UTC, sawyerawesome commented on specs/cloudalertrecord.spec
> +  - name: dynamicExposureStatus
we should also add a timestamp field for exposure status

2024-09-09 22:48 UTC, sawyerawesome requested changes
added comments

2024-09-09 22:58 UTC, knainwal commented on specs/+dynamicexposurealertpayload.spec
> +  - name: publicIP
We will always report IPs.

2024-09-09 23:01 UTC, knainwal commented on specs/cloudalertrecord.spec
> +    subtype: integer
So I left it as integer because I have to query Xpanse using integer IP. I can do conversion before querying Xpanse, or it can be stored here already in integer format. I wan't sure if we already would have it in integer format or string. I would prefer an integer (would be a simple `net.ParseIP(ipStr).To4()` in either case).

2024-09-09 23:09 UTC, knainwal commented on specs/cloudalertrecord.spec
> +  - name: dynamicExposureStatus
Each exposed IP (in a single alert) would have a different timestamp. And I wasn't sure if we want to store all of those (I can do that in the embedded object that I have created for the alert).

The status above is different, as I would set it to POSITIVE even if we have a single embedded object entry in the payload.

2024-09-10 16:05 UTC, sawyerawesome commented on specs/cloudalertrecord.spec
> +    subtype: integer
what's saved here will be used in the alert payload and QA debugging, so string will be preferred

2024-09-10 20:25 UTC, sawyerawesome approved these changes
lgtm

2024-09-10 20:26 UTC, merged